receivers:
  profiling:
    samples_per_second: 97

processors:
  resource/metadata:
    attributes:
      - action: upsert
        key: k8s.cluster.name
        value: demo

  transform/set_service_name:
    profile_statements:
    # Note: This isn't supported today, therefore we do relabeling on the Pyroscope side
    - set(profile.attributes["service_name"], profile.attributes["process.executable.name"])
      where profile.attributes["service_name"] == nil and profile.attributes["process.executable.name"]
      != nil

exporters:
  otlp_grpc:
    endpoint: pyroscope:4040
    tls:
      insecure: true

service:
  pipelines:
    profiles:
      receivers: [profiling]
      exporters: [otlp_grpc]
      processors:
        - resource/metadata
        - transform/set_service_name
