apiVersion: v1
kind: Config
clusters:
- name: shim
  cluster:
    server: http://docker-k8sattributesprocessor-shim:16442
users:
- name: shim
contexts:
- name: shim
  context:
    cluster: shim
    user: shim
current-context: shim
