{
 "title": "Pyroscope Server (Prometheus)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "cpu_utilization{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"disk_.+\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "graph",
   "description": "Number of objects in cache",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"cache_.+_size\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratios",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cache_dicts_hit / (cache_dicts_hit+cache_dicts_miss)",
     "legendFormat": "cache_dicts_hit_rate"
    },
    {
     "expr": "cache_trees_hit / (cache_trees_hit+cache_trees_miss)",
     "legendFormat": "cache_trees_hit_rate"
    },
    {
     "expr": "cache_segments_hit / (cache_segments_hit+cache_segments_miss)",
     "legendFormat": "cache_segments_hit_rate"
    },
    {
     "expr": "cache_dimensions_hit / (cache_dimensions_hit+cache_dimensions_miss)",
     "legendFormat": "cache_dimensions_hit_rate"
    }
   ]
  },
  {
   "title": "Run Progress",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "run_progress", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(successful_uploads[1m])", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"go_memstats_.+bytes\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Upload Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "upload_errors", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Successful Uploads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "successful_uploads", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Badger Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"storage_.+_read\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Badger Writes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"storage_.+_write\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"go_goroutines\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "RAM Evictions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "evictions_alloc_bytes{}", "legendFormat": "{{__name__}}" },
    { "expr": "evictions_total_bytes{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "RAM Evictions Timer",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"evictions_timer\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{__name__=~\"evictions_count\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "RAM Persistence Timer",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"write_back_timer\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{__name__=~\"write_back_count\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Storage Closing Timers",
   "type": "bargauge",
   "description": "They only show up once the server is stopped",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"storage_caches_flush_timer\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{__name__=~\"storage_badger_close_timer\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Retention",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "retention_timer", "legendFormat": "{{__name__}}" },
    { "expr": "retention_count", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}