# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "sinatra", "~> 2.1"
gem 'pyroscope_beta', '= 0.2.1'

gem "thin", "~> 1.8"
