// Code generated by mockery. DO NOT EDIT.

package mockindex

import (
	bbolt "go.etcd.io/bbolt"

	metastorev1 "github.com/grafana/pyroscope/api/gen/proto/go/metastore/v1"

	mock "github.com/stretchr/testify/mock"

	store "github.com/grafana/pyroscope/pkg/experiment/metastore/index/store"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// CreateBuckets provides a mock function with given fields: _a0
func (_m *MockStore) CreateBuckets(_a0 *bbolt.Tx) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateBuckets")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*bbolt.Tx) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_CreateBuckets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBuckets'
type MockStore_CreateBuckets_Call struct {
	*mock.Call
}

// CreateBuckets is a helper method to define mock.On call
//   - _a0 *bbolt.Tx
func (_e *MockStore_Expecter) CreateBuckets(_a0 interface{}) *MockStore_CreateBuckets_Call {
	return &MockStore_CreateBuckets_Call{Call: _e.mock.On("CreateBuckets", _a0)}
}

func (_c *MockStore_CreateBuckets_Call) Run(run func(_a0 *bbolt.Tx)) *MockStore_CreateBuckets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bbolt.Tx))
	})
	return _c
}

func (_c *MockStore_CreateBuckets_Call) Return(_a0 error) *MockStore_CreateBuckets_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_CreateBuckets_Call) RunAndReturn(run func(*bbolt.Tx) error) *MockStore_CreateBuckets_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBlockList provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockStore) DeleteBlockList(_a0 *bbolt.Tx, _a1 store.PartitionKey, _a2 *metastorev1.BlockList) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlockList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*bbolt.Tx, store.PartitionKey, *metastorev1.BlockList) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_DeleteBlockList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBlockList'
type MockStore_DeleteBlockList_Call struct {
	*mock.Call
}

// DeleteBlockList is a helper method to define mock.On call
//   - _a0 *bbolt.Tx
//   - _a1 store.PartitionKey
//   - _a2 *metastorev1.BlockList
func (_e *MockStore_Expecter) DeleteBlockList(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockStore_DeleteBlockList_Call {
	return &MockStore_DeleteBlockList_Call{Call: _e.mock.On("DeleteBlockList", _a0, _a1, _a2)}
}

func (_c *MockStore_DeleteBlockList_Call) Run(run func(_a0 *bbolt.Tx, _a1 store.PartitionKey, _a2 *metastorev1.BlockList)) *MockStore_DeleteBlockList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bbolt.Tx), args[1].(store.PartitionKey), args[2].(*metastorev1.BlockList))
	})
	return _c
}

func (_c *MockStore_DeleteBlockList_Call) Return(_a0 error) *MockStore_DeleteBlockList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_DeleteBlockList_Call) RunAndReturn(run func(*bbolt.Tx, store.PartitionKey, *metastorev1.BlockList) error) *MockStore_DeleteBlockList_Call {
	_c.Call.Return(run)
	return _c
}

// ListPartitions provides a mock function with given fields: _a0
func (_m *MockStore) ListPartitions(_a0 *bbolt.Tx) ([]*store.Partition, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ListPartitions")
	}

	var r0 []*store.Partition
	var r1 error
	if rf, ok := ret.Get(0).(func(*bbolt.Tx) ([]*store.Partition, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*bbolt.Tx) []*store.Partition); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*store.Partition)
		}
	}

	if rf, ok := ret.Get(1).(func(*bbolt.Tx) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListPartitions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPartitions'
type MockStore_ListPartitions_Call struct {
	*mock.Call
}

// ListPartitions is a helper method to define mock.On call
//   - _a0 *bbolt.Tx
func (_e *MockStore_Expecter) ListPartitions(_a0 interface{}) *MockStore_ListPartitions_Call {
	return &MockStore_ListPartitions_Call{Call: _e.mock.On("ListPartitions", _a0)}
}

func (_c *MockStore_ListPartitions_Call) Run(run func(_a0 *bbolt.Tx)) *MockStore_ListPartitions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bbolt.Tx))
	})
	return _c
}

func (_c *MockStore_ListPartitions_Call) Return(_a0 []*store.Partition, _a1 error) *MockStore_ListPartitions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListPartitions_Call) RunAndReturn(run func(*bbolt.Tx) ([]*store.Partition, error)) *MockStore_ListPartitions_Call {
	_c.Call.Return(run)
	return _c
}

// LoadTenantShard provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockStore) LoadTenantShard(_a0 *bbolt.Tx, _a1 store.PartitionKey, _a2 string, _a3 uint32) (*store.TenantShard, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for LoadTenantShard")
	}

	var r0 *store.TenantShard
	var r1 error
	if rf, ok := ret.Get(0).(func(*bbolt.Tx, store.PartitionKey, string, uint32) (*store.TenantShard, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(*bbolt.Tx, store.PartitionKey, string, uint32) *store.TenantShard); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.TenantShard)
		}
	}

	if rf, ok := ret.Get(1).(func(*bbolt.Tx, store.PartitionKey, string, uint32) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_LoadTenantShard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadTenantShard'
type MockStore_LoadTenantShard_Call struct {
	*mock.Call
}

// LoadTenantShard is a helper method to define mock.On call
//   - _a0 *bbolt.Tx
//   - _a1 store.PartitionKey
//   - _a2 string
//   - _a3 uint32
func (_e *MockStore_Expecter) LoadTenantShard(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockStore_LoadTenantShard_Call {
	return &MockStore_LoadTenantShard_Call{Call: _e.mock.On("LoadTenantShard", _a0, _a1, _a2, _a3)}
}

func (_c *MockStore_LoadTenantShard_Call) Run(run func(_a0 *bbolt.Tx, _a1 store.PartitionKey, _a2 string, _a3 uint32)) *MockStore_LoadTenantShard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bbolt.Tx), args[1].(store.PartitionKey), args[2].(string), args[3].(uint32))
	})
	return _c
}

func (_c *MockStore_LoadTenantShard_Call) Return(_a0 *store.TenantShard, _a1 error) *MockStore_LoadTenantShard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_LoadTenantShard_Call) RunAndReturn(run func(*bbolt.Tx, store.PartitionKey, string, uint32) (*store.TenantShard, error)) *MockStore_LoadTenantShard_Call {
	_c.Call.Return(run)
	return _c
}

// StoreBlock provides a mock function with given fields: tx, shard, md
func (_m *MockStore) StoreBlock(tx *bbolt.Tx, shard *store.TenantShard, md *metastorev1.BlockMeta) error {
	ret := _m.Called(tx, shard, md)

	if len(ret) == 0 {
		panic("no return value specified for StoreBlock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*bbolt.Tx, *store.TenantShard, *metastorev1.BlockMeta) error); ok {
		r0 = rf(tx, shard, md)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_StoreBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreBlock'
type MockStore_StoreBlock_Call struct {
	*mock.Call
}

// StoreBlock is a helper method to define mock.On call
//   - tx *bbolt.Tx
//   - shard *store.TenantShard
//   - md *metastorev1.BlockMeta
func (_e *MockStore_Expecter) StoreBlock(tx interface{}, shard interface{}, md interface{}) *MockStore_StoreBlock_Call {
	return &MockStore_StoreBlock_Call{Call: _e.mock.On("StoreBlock", tx, shard, md)}
}

func (_c *MockStore_StoreBlock_Call) Run(run func(tx *bbolt.Tx, shard *store.TenantShard, md *metastorev1.BlockMeta)) *MockStore_StoreBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bbolt.Tx), args[1].(*store.TenantShard), args[2].(*metastorev1.BlockMeta))
	})
	return _c
}

func (_c *MockStore_StoreBlock_Call) Return(_a0 error) *MockStore_StoreBlock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_StoreBlock_Call) RunAndReturn(run func(*bbolt.Tx, *store.TenantShard, *metastorev1.BlockMeta) error) *MockStore_StoreBlock_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
