// Code generated by mockery. DO NOT EDIT.

package mockmetastorev1

import (
	context "context"

	metastorev1 "github.com/grafana/pyroscope/api/gen/proto/go/metastore/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockRaftNodeServiceServer is an autogenerated mock type for the RaftNodeServiceServer type
type MockRaftNodeServiceServer struct {
	mock.Mock
}

type MockRaftNodeServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRaftNodeServiceServer) EXPECT() *MockRaftNodeServiceServer_Expecter {
	return &MockRaftNodeServiceServer_Expecter{mock: &_m.Mock}
}

// ReadIndex provides a mock function with given fields: _a0, _a1
func (_m *MockRaftNodeServiceServer) ReadIndex(_a0 context.Context, _a1 *metastorev1.ReadIndexRequest) (*metastorev1.ReadIndexResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ReadIndex")
	}

	var r0 *metastorev1.ReadIndexResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *metastorev1.ReadIndexRequest) (*metastorev1.ReadIndexResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *metastorev1.ReadIndexRequest) *metastorev1.ReadIndexResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metastorev1.ReadIndexResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *metastorev1.ReadIndexRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRaftNodeServiceServer_ReadIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadIndex'
type MockRaftNodeServiceServer_ReadIndex_Call struct {
	*mock.Call
}

// ReadIndex is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *metastorev1.ReadIndexRequest
func (_e *MockRaftNodeServiceServer_Expecter) ReadIndex(_a0 interface{}, _a1 interface{}) *MockRaftNodeServiceServer_ReadIndex_Call {
	return &MockRaftNodeServiceServer_ReadIndex_Call{Call: _e.mock.On("ReadIndex", _a0, _a1)}
}

func (_c *MockRaftNodeServiceServer_ReadIndex_Call) Run(run func(_a0 context.Context, _a1 *metastorev1.ReadIndexRequest)) *MockRaftNodeServiceServer_ReadIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*metastorev1.ReadIndexRequest))
	})
	return _c
}

func (_c *MockRaftNodeServiceServer_ReadIndex_Call) Return(_a0 *metastorev1.ReadIndexResponse, _a1 error) *MockRaftNodeServiceServer_ReadIndex_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRaftNodeServiceServer_ReadIndex_Call) RunAndReturn(run func(context.Context, *metastorev1.ReadIndexRequest) (*metastorev1.ReadIndexResponse, error)) *MockRaftNodeServiceServer_ReadIndex_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedRaftNodeServiceServer provides a mock function with given fields:
func (_m *MockRaftNodeServiceServer) mustEmbedUnimplementedRaftNodeServiceServer() {
	_m.Called()
}

// MockRaftNodeServiceServer_mustEmbedUnimplementedRaftNodeServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedRaftNodeServiceServer'
type MockRaftNodeServiceServer_mustEmbedUnimplementedRaftNodeServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedRaftNodeServiceServer is a helper method to define mock.On call
func (_e *MockRaftNodeServiceServer_Expecter) mustEmbedUnimplementedRaftNodeServiceServer() *MockRaftNodeServiceServer_mustEmbedUnimplementedRaftNodeServiceServer_Call {
	return &MockRaftNodeServiceServer_mustEmbedUnimplementedRaftNodeServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedRaftNodeServiceServer")}
}

func (_c *MockRaftNodeServiceServer_mustEmbedUnimplementedRaftNodeServiceServer_Call) Run(run func()) *MockRaftNodeServiceServer_mustEmbedUnimplementedRaftNodeServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRaftNodeServiceServer_mustEmbedUnimplementedRaftNodeServiceServer_Call) Return() *MockRaftNodeServiceServer_mustEmbedUnimplementedRaftNodeServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRaftNodeServiceServer_mustEmbedUnimplementedRaftNodeServiceServer_Call) RunAndReturn(run func()) *MockRaftNodeServiceServer_mustEmbedUnimplementedRaftNodeServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRaftNodeServiceServer creates a new instance of MockRaftNodeServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRaftNodeServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRaftNodeServiceServer {
	mock := &MockRaftNodeServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
