// Code generated by mockery. DO NOT EDIT.

package mockmetastorev1

import (
	context "context"

	metastorev1 "github.com/grafana/pyroscope/api/gen/proto/go/metastore/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockIndexServiceServer is an autogenerated mock type for the IndexServiceServer type
type MockIndexServiceServer struct {
	mock.Mock
}

type MockIndexServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIndexServiceServer) EXPECT() *MockIndexServiceServer_Expecter {
	return &MockIndexServiceServer_Expecter{mock: &_m.Mock}
}

// AddBlock provides a mock function with given fields: _a0, _a1
func (_m *MockIndexServiceServer) AddBlock(_a0 context.Context, _a1 *metastorev1.AddBlockRequest) (*metastorev1.AddBlockResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AddBlock")
	}

	var r0 *metastorev1.AddBlockResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *metastorev1.AddBlockRequest) (*metastorev1.AddBlockResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *metastorev1.AddBlockRequest) *metastorev1.AddBlockResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metastorev1.AddBlockResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *metastorev1.AddBlockRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIndexServiceServer_AddBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBlock'
type MockIndexServiceServer_AddBlock_Call struct {
	*mock.Call
}

// AddBlock is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *metastorev1.AddBlockRequest
func (_e *MockIndexServiceServer_Expecter) AddBlock(_a0 interface{}, _a1 interface{}) *MockIndexServiceServer_AddBlock_Call {
	return &MockIndexServiceServer_AddBlock_Call{Call: _e.mock.On("AddBlock", _a0, _a1)}
}

func (_c *MockIndexServiceServer_AddBlock_Call) Run(run func(_a0 context.Context, _a1 *metastorev1.AddBlockRequest)) *MockIndexServiceServer_AddBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*metastorev1.AddBlockRequest))
	})
	return _c
}

func (_c *MockIndexServiceServer_AddBlock_Call) Return(_a0 *metastorev1.AddBlockResponse, _a1 error) *MockIndexServiceServer_AddBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIndexServiceServer_AddBlock_Call) RunAndReturn(run func(context.Context, *metastorev1.AddBlockRequest) (*metastorev1.AddBlockResponse, error)) *MockIndexServiceServer_AddBlock_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockMetadata provides a mock function with given fields: _a0, _a1
func (_m *MockIndexServiceServer) GetBlockMetadata(_a0 context.Context, _a1 *metastorev1.GetBlockMetadataRequest) (*metastorev1.GetBlockMetadataResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockMetadata")
	}

	var r0 *metastorev1.GetBlockMetadataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *metastorev1.GetBlockMetadataRequest) (*metastorev1.GetBlockMetadataResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *metastorev1.GetBlockMetadataRequest) *metastorev1.GetBlockMetadataResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metastorev1.GetBlockMetadataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *metastorev1.GetBlockMetadataRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIndexServiceServer_GetBlockMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockMetadata'
type MockIndexServiceServer_GetBlockMetadata_Call struct {
	*mock.Call
}

// GetBlockMetadata is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *metastorev1.GetBlockMetadataRequest
func (_e *MockIndexServiceServer_Expecter) GetBlockMetadata(_a0 interface{}, _a1 interface{}) *MockIndexServiceServer_GetBlockMetadata_Call {
	return &MockIndexServiceServer_GetBlockMetadata_Call{Call: _e.mock.On("GetBlockMetadata", _a0, _a1)}
}

func (_c *MockIndexServiceServer_GetBlockMetadata_Call) Run(run func(_a0 context.Context, _a1 *metastorev1.GetBlockMetadataRequest)) *MockIndexServiceServer_GetBlockMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*metastorev1.GetBlockMetadataRequest))
	})
	return _c
}

func (_c *MockIndexServiceServer_GetBlockMetadata_Call) Return(_a0 *metastorev1.GetBlockMetadataResponse, _a1 error) *MockIndexServiceServer_GetBlockMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIndexServiceServer_GetBlockMetadata_Call) RunAndReturn(run func(context.Context, *metastorev1.GetBlockMetadataRequest) (*metastorev1.GetBlockMetadataResponse, error)) *MockIndexServiceServer_GetBlockMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedIndexServiceServer provides a mock function with given fields:
func (_m *MockIndexServiceServer) mustEmbedUnimplementedIndexServiceServer() {
	_m.Called()
}

// MockIndexServiceServer_mustEmbedUnimplementedIndexServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedIndexServiceServer'
type MockIndexServiceServer_mustEmbedUnimplementedIndexServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedIndexServiceServer is a helper method to define mock.On call
func (_e *MockIndexServiceServer_Expecter) mustEmbedUnimplementedIndexServiceServer() *MockIndexServiceServer_mustEmbedUnimplementedIndexServiceServer_Call {
	return &MockIndexServiceServer_mustEmbedUnimplementedIndexServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedIndexServiceServer")}
}

func (_c *MockIndexServiceServer_mustEmbedUnimplementedIndexServiceServer_Call) Run(run func()) *MockIndexServiceServer_mustEmbedUnimplementedIndexServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIndexServiceServer_mustEmbedUnimplementedIndexServiceServer_Call) Return() *MockIndexServiceServer_mustEmbedUnimplementedIndexServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIndexServiceServer_mustEmbedUnimplementedIndexServiceServer_Call) RunAndReturn(run func()) *MockIndexServiceServer_mustEmbedUnimplementedIndexServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIndexServiceServer creates a new instance of MockIndexServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIndexServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIndexServiceServer {
	mock := &MockIndexServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
