version: v1
source_code:
  mappings:
    - path:
        - prefix: $GOROOT/src
      language: go
      source:
       github:
        owner: golang
        repo: go
        ref: go1.25.7
        path: src
