package symdb

import (
	"iter"
	"unique"

	googlev1 "github.com/grafana/pyroscope/api/gen/proto/go/google/v1"
	queryv1 "github.com/grafana/pyroscope/api/gen/proto/go/query/v1"
	"github.com/grafana/pyroscope/pkg/model"
)

// TODO(simonswine): If successful upstream those InMemory types into schemav1
type InMemoryLine struct {
	// The id of the corresponding profile.Function for this line.
	FunctionId InlineFunction
	// Line number in source code.
	Line int32
}

type InMemoryLocation struct {
	Address   uint64
	MappingId InlineMapping
	IsFolded  bool
	Line      [8]InMemoryLine
}

type InMemoryMapping struct {
	// Address at which the binary (or DLL) is loaded into memory.
	MemoryStart uint64
	// The limit of the address range occupied by this mapping.
	MemoryLimit uint64
	// Offset in the binary that corresponds to the first mapped address.
	FileOffset uint64
	// The object this entry is loaded from.  This can be a filename on
	// disk for the main binary and shared libraries, or virtual
	// abstractions like "[vdso]".
	Filename unique.Handle[string]
	// A string that uniquely identifies a particular program version
	// with high probability. E.g., for binaries generated by GNU tools,
	// it could be the contents of the .note.gnu.build-id field.
	BuildId unique.Handle[string]
	// The following fields indicate the resolution of symbolic info.
	HasFunctions    bool
	HasFilenames    bool
	HasLineNumbers  bool
	HasInlineFrames bool
}

type InMemoryFunction struct {
	// Name of the function, in human-readable form if available.
	Name unique.Handle[string]
	// Name of the function, as identified by the system.
	// For instance, it can be a C++ mangled name.
	SystemName unique.Handle[string]
	// Source file containing the function.
	Filename unique.Handle[string]
	// Line number in source file.
	StartLine unique.Handle[string]
}

type InlineMapping = unique.Handle[InMemoryMapping]
type InlineLocation = unique.Handle[InMemoryLocation]
type InlineFunction = unique.Handle[InMemoryFunction]

type symbolMerger struct {
	locationsLookup map[InlineLocation]int
	locations       []InlineLocation
}

func newSymbolMerger() *symbolMerger {
	return &symbolMerger{
		locationsLookup: make(map[InlineLocation]int),
	}
}

func (m *symbolMerger) add(symbols *Symbols) func(model.LocationRefName) model.LocationRefName {
	adder := newAdder(symbols)

	return func(in model.LocationRefName) model.LocationRefName {
		// Get the unique location handle for this location
		loc := adder.getLoc(int(in))

		// Look up if we've already seen this location
		if idx, ok := m.locationsLookup[loc]; ok {
			return model.LocationRefName(idx)
		}

		// New location - add it to our merged list
		idx := len(m.locations)
		m.locations = append(m.locations, loc)
		m.locationsLookup[loc] = idx

		return model.LocationRefName(idx)
	}
}

// This should append strings, mappings, functions, locations to the TreeSymbols, ensuring via maps that each element is unique.
func (m *symbolMerger) resultBuilder() *symbolResultBuilder {
	return &symbolResultBuilder{
		allLocations:    m.locations,
		locationsLookup: make(map[InlineLocation]int),
		locationsRef:    make([]int, 0, len(m.locations)),
	}
}

var (
	lZero = InlineLocation{}
	mZero = InlineMapping{}
	fZero = InlineFunction{}
	sZero = unique.Handle[string]{}
)

type symbolAdder struct {
	symbols *Symbols
	lCache  []InlineLocation
	mCache  []InlineMapping
	fCache  []InlineFunction
	sCache  []unique.Handle[string]
}

func newAdder(symbols *Symbols) *symbolAdder {
	return &symbolAdder{
		symbols: symbols,
		lCache:  make([]InlineLocation, len(symbols.Locations)),
		mCache:  make([]InlineMapping, len(symbols.Mappings)),
		fCache:  make([]InlineFunction, len(symbols.Functions)),
		sCache:  make([]unique.Handle[string], len(symbols.Strings)),
	}
}

func (a *symbolAdder) getLoc(locID int) InlineLocation {
	if r := a.lCache[locID]; r != lZero {
		return r
	}

	loc := a.symbols.Locations[locID]

	nLoc := InMemoryLocation{
		Address:   loc.Address,
		MappingId: a.getMap(int(loc.MappingId)),
	}

	for idx, line := range loc.Line {
		if idx > 7 {
			panic("not ready for more than 8 inlines")
		}
		nLoc.Line[idx].FunctionId = a.getFunc(int(line.FunctionId))
		nLoc.Line[idx].Line = line.Line
	}

	h := unique.Make(nLoc)
	a.lCache[locID] = h

	return h
}

func (a *symbolAdder) getMap(mapID int) InlineMapping {
	if r := a.mCache[mapID]; r != mZero {
		return r
	}

	m := a.symbols.Mappings[mapID]

	nMap := InMemoryMapping{
		MemoryStart:     m.MemoryStart,
		MemoryLimit:     m.MemoryLimit,
		FileOffset:      m.FileOffset,
		Filename:        a.getString(m.Filename),
		BuildId:         a.getString(m.BuildId),
		HasFunctions:    m.HasFunctions,
		HasFilenames:    m.HasFilenames,
		HasLineNumbers:  m.HasLineNumbers,
		HasInlineFrames: m.HasInlineFrames,
	}

	h := unique.Make(nMap)
	a.mCache[mapID] = h

	return h
}

func (a *symbolAdder) getFunc(funcID int) InlineFunction {
	if r := a.fCache[funcID]; r != fZero {
		return r
	}

	f := a.symbols.Functions[funcID]

	nFunc := InMemoryFunction{
		Name:       a.getString(f.Name),
		SystemName: a.getString(f.SystemName),
		Filename:   a.getString(f.Filename),
		StartLine:  a.getString(f.StartLine),
	}

	h := unique.Make(nFunc)
	a.fCache[funcID] = h

	return h
}

func (a *symbolAdder) getString(strID uint32) unique.Handle[string] {
	if strID == 0 {
		return unique.Make("")
	}

	if r := a.sCache[strID]; r != (unique.Handle[string]{}) {
		return r
	}

	str := a.symbols.Strings[strID]
	h := unique.Make(str)
	a.sCache[strID] = h

	return h
}

type lookup[K comparable] struct {
	count int
	m     map[K]int
}

func newLookup[K comparable]() *lookup[K] {
	return &lookup[K]{
		m: make(map[K]int),
	}
}

func (l lookup[K]) get(v K) int {
	if v, ok := l.m[v]; ok {
		return v
	}
	r := l.count
	l.count += 1
	l.m[v] = r
	return r
}

func (l lookup[K]) len() int {
	return len(l.m)
}

func (l lookup[K]) iter() iter.Seq2[int, K] {
	return func(yield func(int, K) bool) {
		for k, v := range l.m {
			if !yield(v, k) {
				return
			}
		}
	}
}

type symbolResultBuilder struct {
	allLocations []InlineLocation

	locationsLookup map[InlineLocation]int
	locationsRef    []int
}

func (m *symbolResultBuilder) KeepSymbol(in model.LocationRefName) model.LocationRefName {
	h := m.allLocations[in]

	v, ok := m.locationsLookup[h]
	if ok {
		return model.LocationRefName(v)
	}

	v = len(m.locationsRef)
	m.locationsLookup[h] = v
	m.locationsRef = append(m.locationsRef, int(in))
	return model.LocationRefName(v)

}

// This should append strings, mappings, functions, locations to the TreeSymbols, ensuring via maps that each element is unique.
func (m *symbolResultBuilder) Build(r *queryv1.TreeSymbols) {
	var (
		mappings  = newLookup[InlineMapping]()
		functions = newLookup[InlineFunction]()
		strings   = newLookup[unique.Handle[string]]()
	)

	// first resolve all locations
	r.Locations = make([]*googlev1.Location, len(m.locationsRef))
	locationsObj := make([]googlev1.Location, len(m.locationsRef))
	for idx, ref := range m.locationsRef {
		orig := m.allLocations[ref].Value()
		loc := &locationsObj[idx]
		loc.MappingId = uint64(mappings.get(orig.MappingId))
		loc.Address = orig.Address
		loc.Id = uint64(idx)
		loc.IsFolded = orig.IsFolded
		for _, line := range orig.Line {
			if line.FunctionId == fZero {
				break
			}
			loc.Line = append(loc.Line,
				&googlev1.Line{
					FunctionId: uint64(functions.get(line.FunctionId)),
					Line:       int64(line.Line),
				},
			)
		}
		r.Locations[idx] = loc
	}

	// now go through all mappings
	r.Mappings = make([]*googlev1.Mapping, mappings.len())
	mappingsObj := make([]googlev1.Mapping, mappings.len())
	for idx, ref := range mappings.iter() {
		orig := ref.Value()
		mapp := &mappingsObj[idx]
		mapp.Id = uint64(idx)
		mapp.MemoryStart = orig.MemoryStart
		mapp.MemoryLimit = orig.MemoryLimit
		mapp.FileOffset = orig.FileOffset
		mapp.Filename = int64(strings.get(orig.Filename))
		mapp.BuildId = int64(strings.get(orig.BuildId))
		mapp.HasFunctions = orig.HasFunctions
		mapp.HasFilenames = orig.HasFilenames
		mapp.HasLineNumbers = orig.HasLineNumbers
		mapp.HasInlineFrames = orig.HasInlineFrames
		r.Mappings[idx] = mapp
	}

	// now go through all functions
	r.Functions = make([]*googlev1.Function, functions.len())
	functionsObj := make([]googlev1.Function, functions.len())
	for idx, ref := range functions.iter() {
		orig := ref.Value()
		fn := &functionsObj[idx]
		fn.Id = uint64(idx)
		fn.Name = int64(strings.get(orig.Name))
		fn.SystemName = int64(strings.get(orig.SystemName))
		fn.Filename = int64(strings.get(orig.Filename))
		fn.StartLine = int64(strings.get(orig.StartLine))
		r.Functions[idx] = fn
	}

	// now go through all strings
	r.Strings = make([]string, strings.len())
	for idx, ref := range strings.iter() {
		r.Strings[idx] = ref.Value()
	}

	return
}
