// SPDX-License-Identifier: AGPL-3.0-only
// Provenance-includes-location: https://github.com/cortexproject/cortex/blob/master/pkg/scheduler/schedulerpb/scheduler.proto
// Provenance-includes-license: Apache-2.0
// Provenance-includes-copyright: The Cortex Authors.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: scheduler/schedulerpb/scheduler.proto

package schedulerpb

import (
	httpgrpc "github.com/grafana/pyroscope/pkg/util/httpgrpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrontendToSchedulerType int32

const (
	FrontendToSchedulerType_INIT    FrontendToSchedulerType = 0
	FrontendToSchedulerType_ENQUEUE FrontendToSchedulerType = 1
	FrontendToSchedulerType_CANCEL  FrontendToSchedulerType = 2
)

// Enum value maps for FrontendToSchedulerType.
var (
	FrontendToSchedulerType_name = map[int32]string{
		0: "INIT",
		1: "ENQUEUE",
		2: "CANCEL",
	}
	FrontendToSchedulerType_value = map[string]int32{
		"INIT":    0,
		"ENQUEUE": 1,
		"CANCEL":  2,
	}
)

func (x FrontendToSchedulerType) Enum() *FrontendToSchedulerType {
	p := new(FrontendToSchedulerType)
	*p = x
	return p
}

func (x FrontendToSchedulerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrontendToSchedulerType) Descriptor() protoreflect.EnumDescriptor {
	return file_scheduler_schedulerpb_scheduler_proto_enumTypes[0].Descriptor()
}

func (FrontendToSchedulerType) Type() protoreflect.EnumType {
	return &file_scheduler_schedulerpb_scheduler_proto_enumTypes[0]
}

func (x FrontendToSchedulerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrontendToSchedulerType.Descriptor instead.
func (FrontendToSchedulerType) EnumDescriptor() ([]byte, []int) {
	return file_scheduler_schedulerpb_scheduler_proto_rawDescGZIP(), []int{0}
}

type SchedulerToFrontendStatus int32

const (
	SchedulerToFrontendStatus_OK                           SchedulerToFrontendStatus = 0
	SchedulerToFrontendStatus_TOO_MANY_REQUESTS_PER_TENANT SchedulerToFrontendStatus = 1
	SchedulerToFrontendStatus_ERROR                        SchedulerToFrontendStatus = 2
	SchedulerToFrontendStatus_SHUTTING_DOWN                SchedulerToFrontendStatus = 3
)

// Enum value maps for SchedulerToFrontendStatus.
var (
	SchedulerToFrontendStatus_name = map[int32]string{
		0: "OK",
		1: "TOO_MANY_REQUESTS_PER_TENANT",
		2: "ERROR",
		3: "SHUTTING_DOWN",
	}
	SchedulerToFrontendStatus_value = map[string]int32{
		"OK":                           0,
		"TOO_MANY_REQUESTS_PER_TENANT": 1,
		"ERROR":                        2,
		"SHUTTING_DOWN":                3,
	}
)

func (x SchedulerToFrontendStatus) Enum() *SchedulerToFrontendStatus {
	p := new(SchedulerToFrontendStatus)
	*p = x
	return p
}

func (x SchedulerToFrontendStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchedulerToFrontendStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_scheduler_schedulerpb_scheduler_proto_enumTypes[1].Descriptor()
}

func (SchedulerToFrontendStatus) Type() protoreflect.EnumType {
	return &file_scheduler_schedulerpb_scheduler_proto_enumTypes[1]
}

func (x SchedulerToFrontendStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchedulerToFrontendStatus.Descriptor instead.
func (SchedulerToFrontendStatus) EnumDescriptor() ([]byte, []int) {
	return file_scheduler_schedulerpb_scheduler_proto_rawDescGZIP(), []int{1}
}

// Querier reports its own clientID when it connects, so that scheduler knows how many *different* queriers are connected.
// To signal that querier is ready to accept another request, querier sends empty message.
type QuerierToScheduler struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuerierID     string                 `protobuf:"bytes,1,opt,name=querierID,proto3" json:"querierID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerierToScheduler) Reset() {
	*x = QuerierToScheduler{}
	mi := &file_scheduler_schedulerpb_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerierToScheduler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerierToScheduler) ProtoMessage() {}

func (x *QuerierToScheduler) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_schedulerpb_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerierToScheduler.ProtoReflect.Descriptor instead.
func (*QuerierToScheduler) Descriptor() ([]byte, []int) {
	return file_scheduler_schedulerpb_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *QuerierToScheduler) GetQuerierID() string {
	if x != nil {
		return x.QuerierID
	}
	return ""
}

type SchedulerToQuerier struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Query ID as reported by frontend. When querier sends the response back to frontend (using frontendAddress),
	// it identifies the query by using this ID.
	QueryID     uint64                `protobuf:"varint,1,opt,name=queryID,proto3" json:"queryID,omitempty"`
	HttpRequest *httpgrpc.HTTPRequest `protobuf:"bytes,2,opt,name=httpRequest,proto3" json:"httpRequest,omitempty"`
	// Where should querier send HTTP Response to (using FrontendForQuerier interface).
	FrontendAddress string `protobuf:"bytes,3,opt,name=frontendAddress,proto3" json:"frontendAddress,omitempty"`
	// User who initiated the request. Needed to send reply back to frontend.
	UserID string `protobuf:"bytes,4,opt,name=userID,proto3" json:"userID,omitempty"`
	// Whether query statistics tracking should be enabled. The response will include
	// statistics only when this option is enabled.
	StatsEnabled  bool `protobuf:"varint,5,opt,name=statsEnabled,proto3" json:"statsEnabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulerToQuerier) Reset() {
	*x = SchedulerToQuerier{}
	mi := &file_scheduler_schedulerpb_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerToQuerier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerToQuerier) ProtoMessage() {}

func (x *SchedulerToQuerier) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_schedulerpb_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerToQuerier.ProtoReflect.Descriptor instead.
func (*SchedulerToQuerier) Descriptor() ([]byte, []int) {
	return file_scheduler_schedulerpb_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *SchedulerToQuerier) GetQueryID() uint64 {
	if x != nil {
		return x.QueryID
	}
	return 0
}

func (x *SchedulerToQuerier) GetHttpRequest() *httpgrpc.HTTPRequest {
	if x != nil {
		return x.HttpRequest
	}
	return nil
}

func (x *SchedulerToQuerier) GetFrontendAddress() string {
	if x != nil {
		return x.FrontendAddress
	}
	return ""
}

func (x *SchedulerToQuerier) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SchedulerToQuerier) GetStatsEnabled() bool {
	if x != nil {
		return x.StatsEnabled
	}
	return false
}

type FrontendToScheduler struct {
	state protoimpl.MessageState  `protogen:"open.v1"`
	Type  FrontendToSchedulerType `protobuf:"varint,1,opt,name=type,proto3,enum=schedulerpb.FrontendToSchedulerType" json:"type,omitempty"`
	// Used by INIT message. Will be put into all requests passed to querier.
	FrontendAddress string `protobuf:"bytes,2,opt,name=frontendAddress,proto3" json:"frontendAddress,omitempty"`
	// Used by ENQUEUE and CANCEL.
	// Each frontend manages its own queryIDs. Different frontends may use same set of query IDs.
	QueryID uint64 `protobuf:"varint,3,opt,name=queryID,proto3" json:"queryID,omitempty"`
	// Following are used by ENQUEUE only.
	UserID        string                `protobuf:"bytes,4,opt,name=userID,proto3" json:"userID,omitempty"`
	HttpRequest   *httpgrpc.HTTPRequest `protobuf:"bytes,5,opt,name=httpRequest,proto3" json:"httpRequest,omitempty"`
	StatsEnabled  bool                  `protobuf:"varint,6,opt,name=statsEnabled,proto3" json:"statsEnabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontendToScheduler) Reset() {
	*x = FrontendToScheduler{}
	mi := &file_scheduler_schedulerpb_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontendToScheduler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontendToScheduler) ProtoMessage() {}

func (x *FrontendToScheduler) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_schedulerpb_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontendToScheduler.ProtoReflect.Descriptor instead.
func (*FrontendToScheduler) Descriptor() ([]byte, []int) {
	return file_scheduler_schedulerpb_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *FrontendToScheduler) GetType() FrontendToSchedulerType {
	if x != nil {
		return x.Type
	}
	return FrontendToSchedulerType_INIT
}

func (x *FrontendToScheduler) GetFrontendAddress() string {
	if x != nil {
		return x.FrontendAddress
	}
	return ""
}

func (x *FrontendToScheduler) GetQueryID() uint64 {
	if x != nil {
		return x.QueryID
	}
	return 0
}

func (x *FrontendToScheduler) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *FrontendToScheduler) GetHttpRequest() *httpgrpc.HTTPRequest {
	if x != nil {
		return x.HttpRequest
	}
	return nil
}

func (x *FrontendToScheduler) GetStatsEnabled() bool {
	if x != nil {
		return x.StatsEnabled
	}
	return false
}

type SchedulerToFrontend struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        SchedulerToFrontendStatus `protobuf:"varint,1,opt,name=status,proto3,enum=schedulerpb.SchedulerToFrontendStatus" json:"status,omitempty"`
	Error         string                    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulerToFrontend) Reset() {
	*x = SchedulerToFrontend{}
	mi := &file_scheduler_schedulerpb_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerToFrontend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerToFrontend) ProtoMessage() {}

func (x *SchedulerToFrontend) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_schedulerpb_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerToFrontend.ProtoReflect.Descriptor instead.
func (*SchedulerToFrontend) Descriptor() ([]byte, []int) {
	return file_scheduler_schedulerpb_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *SchedulerToFrontend) GetStatus() SchedulerToFrontendStatus {
	if x != nil {
		return x.Status
	}
	return SchedulerToFrontendStatus_OK
}

func (x *SchedulerToFrontend) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NotifyQuerierShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuerierID     string                 `protobuf:"bytes,1,opt,name=querierID,proto3" json:"querierID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyQuerierShutdownRequest) Reset() {
	*x = NotifyQuerierShutdownRequest{}
	mi := &file_scheduler_schedulerpb_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyQuerierShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyQuerierShutdownRequest) ProtoMessage() {}

func (x *NotifyQuerierShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_schedulerpb_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyQuerierShutdownRequest.ProtoReflect.Descriptor instead.
func (*NotifyQuerierShutdownRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_schedulerpb_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *NotifyQuerierShutdownRequest) GetQuerierID() string {
	if x != nil {
		return x.QuerierID
	}
	return ""
}

type NotifyQuerierShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyQuerierShutdownResponse) Reset() {
	*x = NotifyQuerierShutdownResponse{}
	mi := &file_scheduler_schedulerpb_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyQuerierShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyQuerierShutdownResponse) ProtoMessage() {}

func (x *NotifyQuerierShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_schedulerpb_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyQuerierShutdownResponse.ProtoReflect.Descriptor instead.
func (*NotifyQuerierShutdownResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_schedulerpb_scheduler_proto_rawDescGZIP(), []int{5}
}

var File_scheduler_schedulerpb_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_schedulerpb_scheduler_proto_rawDesc = "" +
	"\n" +
	"%scheduler/schedulerpb/scheduler.proto\x12\vschedulerpb\x1a\x1cutil/httpgrpc/httpgrpc.proto\"2\n" +
	"\x12QuerierToScheduler\x12\x1c\n" +
	"\tquerierID\x18\x01 \x01(\tR\tquerierID\"\xcd\x01\n" +
	"\x12SchedulerToQuerier\x12\x18\n" +
	"\aqueryID\x18\x01 \x01(\x04R\aqueryID\x127\n" +
	"\vhttpRequest\x18\x02 \x01(\v2\x15.httpgrpc.HTTPRequestR\vhttpRequest\x12(\n" +
	"\x0ffrontendAddress\x18\x03 \x01(\tR\x0ffrontendAddress\x12\x16\n" +
	"\x06userID\x18\x04 \x01(\tR\x06userID\x12\"\n" +
	"\fstatsEnabled\x18\x05 \x01(\bR\fstatsEnabled\"\x88\x02\n" +
	"\x13FrontendToScheduler\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.schedulerpb.FrontendToSchedulerTypeR\x04type\x12(\n" +
	"\x0ffrontendAddress\x18\x02 \x01(\tR\x0ffrontendAddress\x12\x18\n" +
	"\aqueryID\x18\x03 \x01(\x04R\aqueryID\x12\x16\n" +
	"\x06userID\x18\x04 \x01(\tR\x06userID\x127\n" +
	"\vhttpRequest\x18\x05 \x01(\v2\x15.httpgrpc.HTTPRequestR\vhttpRequest\x12\"\n" +
	"\fstatsEnabled\x18\x06 \x01(\bR\fstatsEnabled\"k\n" +
	"\x13SchedulerToFrontend\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.schedulerpb.SchedulerToFrontendStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"<\n" +
	"\x1cNotifyQuerierShutdownRequest\x12\x1c\n" +
	"\tquerierID\x18\x01 \x01(\tR\tquerierID\"\x1f\n" +
	"\x1dNotifyQuerierShutdownResponse*<\n" +
	"\x17FrontendToSchedulerType\x12\b\n" +
	"\x04INIT\x10\x00\x12\v\n" +
	"\aENQUEUE\x10\x01\x12\n" +
	"\n" +
	"\x06CANCEL\x10\x02*c\n" +
	"\x19SchedulerToFrontendStatus\x12\x06\n" +
	"\x02OK\x10\x00\x12 \n" +
	"\x1cTOO_MANY_REQUESTS_PER_TENANT\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\x11\n" +
	"\rSHUTTING_DOWN\x10\x032\xdc\x01\n" +
	"\x13SchedulerForQuerier\x12U\n" +
	"\vQuerierLoop\x12\x1f.schedulerpb.QuerierToScheduler\x1a\x1f.schedulerpb.SchedulerToQuerier\"\x00(\x010\x01\x12n\n" +
	"\x15NotifyQuerierShutdown\x12).schedulerpb.NotifyQuerierShutdownRequest\x1a*.schedulerpb.NotifyQuerierShutdownResponse2p\n" +
	"\x14SchedulerForFrontend\x12X\n" +
	"\fFrontendLoop\x12 .schedulerpb.FrontendToScheduler\x1a .schedulerpb.SchedulerToFrontend\"\x00(\x010\x01B\xa5\x01\n" +
	"\x0fcom.schedulerpbB\x0eSchedulerProtoP\x01Z6github.com/grafana/pyroscope/pkg/scheduler/schedulerpb\xa2\x02\x03SXX\xaa\x02\vSchedulerpb\xca\x02\vSchedulerpb\xe2\x02\x17Schedulerpb\\GPBMetadata\xea\x02\vSchedulerpbb\x06proto3"

var (
	file_scheduler_schedulerpb_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_schedulerpb_scheduler_proto_rawDescData []byte
)

func file_scheduler_schedulerpb_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_schedulerpb_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_schedulerpb_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_schedulerpb_scheduler_proto_rawDesc), len(file_scheduler_schedulerpb_scheduler_proto_rawDesc)))
	})
	return file_scheduler_schedulerpb_scheduler_proto_rawDescData
}

var file_scheduler_schedulerpb_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_scheduler_schedulerpb_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_scheduler_schedulerpb_scheduler_proto_goTypes = []any{
	(FrontendToSchedulerType)(0),          // 0: schedulerpb.FrontendToSchedulerType
	(SchedulerToFrontendStatus)(0),        // 1: schedulerpb.SchedulerToFrontendStatus
	(*QuerierToScheduler)(nil),            // 2: schedulerpb.QuerierToScheduler
	(*SchedulerToQuerier)(nil),            // 3: schedulerpb.SchedulerToQuerier
	(*FrontendToScheduler)(nil),           // 4: schedulerpb.FrontendToScheduler
	(*SchedulerToFrontend)(nil),           // 5: schedulerpb.SchedulerToFrontend
	(*NotifyQuerierShutdownRequest)(nil),  // 6: schedulerpb.NotifyQuerierShutdownRequest
	(*NotifyQuerierShutdownResponse)(nil), // 7: schedulerpb.NotifyQuerierShutdownResponse
	(*httpgrpc.HTTPRequest)(nil),          // 8: httpgrpc.HTTPRequest
}
var file_scheduler_schedulerpb_scheduler_proto_depIdxs = []int32{
	8, // 0: schedulerpb.SchedulerToQuerier.httpRequest:type_name -> httpgrpc.HTTPRequest
	0, // 1: schedulerpb.FrontendToScheduler.type:type_name -> schedulerpb.FrontendToSchedulerType
	8, // 2: schedulerpb.FrontendToScheduler.httpRequest:type_name -> httpgrpc.HTTPRequest
	1, // 3: schedulerpb.SchedulerToFrontend.status:type_name -> schedulerpb.SchedulerToFrontendStatus
	2, // 4: schedulerpb.SchedulerForQuerier.QuerierLoop:input_type -> schedulerpb.QuerierToScheduler
	6, // 5: schedulerpb.SchedulerForQuerier.NotifyQuerierShutdown:input_type -> schedulerpb.NotifyQuerierShutdownRequest
	4, // 6: schedulerpb.SchedulerForFrontend.FrontendLoop:input_type -> schedulerpb.FrontendToScheduler
	3, // 7: schedulerpb.SchedulerForQuerier.QuerierLoop:output_type -> schedulerpb.SchedulerToQuerier
	7, // 8: schedulerpb.SchedulerForQuerier.NotifyQuerierShutdown:output_type -> schedulerpb.NotifyQuerierShutdownResponse
	5, // 9: schedulerpb.SchedulerForFrontend.FrontendLoop:output_type -> schedulerpb.SchedulerToFrontend
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_scheduler_schedulerpb_scheduler_proto_init() }
func file_scheduler_schedulerpb_scheduler_proto_init() {
	if File_scheduler_schedulerpb_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_schedulerpb_scheduler_proto_rawDesc), len(file_scheduler_schedulerpb_scheduler_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_scheduler_schedulerpb_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_schedulerpb_scheduler_proto_depIdxs,
		EnumInfos:         file_scheduler_schedulerpb_scheduler_proto_enumTypes,
		MessageInfos:      file_scheduler_schedulerpb_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_schedulerpb_scheduler_proto = out.File
	file_scheduler_schedulerpb_scheduler_proto_goTypes = nil
	file_scheduler_schedulerpb_scheduler_proto_depIdxs = nil
}
