{
 "title": "Simple Go App",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "App Slow function CPU time (Total, 5m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(app_slow_function_env_cpu_seconds_total{}[5m])",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "App Slow function CPU time (Percent, 1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(app_slow_function_env_cpu_seconds_total{}[1m])/60",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "App Alloc Objects (Total, 5m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(app_alloc_objects_total{}[5m])",
     "legendFormat": "alloc objects"
    }
   ]
  },
  {
   "title": "App Alloc Space (Total, 5m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(app_alloc_space_bytes{}[5m])",
     "legendFormat": "alloc space"
    }
   ]
  },
  {
   "title": "App Inuse Objects (Avg, 5m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(app_inuse_objects_total{}[5m])/30",
     "legendFormat": "inuse objects"
    }
   ]
  },
  {
   "title": "App Inuse Space (Total, 5m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(app_inuse_space_bytes{}[5m])/30",
     "legendFormat": "inuse space"
    }
   ]
  }
 ]
}