# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'pyroscope', '= 0.5.10'
gem "sinatra", "~> 2.1"

gem "thin", "~> 1.8"
