{
 "title": "main",
 "time": { "from": "2021-05-27T01:20:30.085Z", "to": "now" },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.pyroscope-server.mem.*)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.pyroscope-server.disk.*)"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "graph",
   "description": "Number of objects in cache",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.pyroscope-server.cache.*)"
    }
   ]
  },
  {
   "title": "Times",
   "type": "table",
   "description": "a lot symbols are replaces with dashes or removed",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "target": "aliasSub(aliasByMetric(stats.gauges.pyroscope-server.times.*), '---', '=')"
    }
   ]
  },
  {
   "title": "Environment",
   "type": "table",
   "description": "a lot symbols are replaces with dashes or removed",
   "gridPos": { "h": 15, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "target": "aliasSub(aliasByMetric(stats.gauges.pyroscope-server.env.*), '---', '=')"
    }
   ]
  }
 ]
}