# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'pyroscope', '= 0.6.7'
gem "sinatra", "~> 4.1"
gem "thin", "~> 2.0"
gem 'pyroscope-otel'
gem 'opentelemetry-sdk'
gem 'opentelemetry-exporter-otlp'

gem "rackup", "~> 2.2"
gem "puma", "~> 6.6"
