export const SET_DATE_RANGE = 'SET_DATE_RANGE';
export const SET_FROM = 'SET_FROM';
export const SET_UNTIL = 'SET_UNTIL';
export const SET_MAX_NODES = 'SET_MAX_NODES';
export const SET_QUERY = 'SET_QUERY';
export const REFRESH = 'REFRESH';

export const REQUEST_PYROSCOPE_APP_DATA = 'REQUEST_PYROSCOPE_APP_DATA';
export const RECEIVE_PYROSCOPE_APP_DATA = 'RECEIVE_PYROSCOPE_APP_DATA';
export const CANCEL_PYROSCOPE_APP_DATA = 'CANCEL_PYROSCOPE_APP_DATA';

export const REQUEST_COMPARISON_APP_DATA = 'REQUEST_COMPARISON_APP_DATA';
export const RECEIVE_COMPARISON_APP_DATA = 'RECEIVE_COMPARISON_APP_DATA';
export const CANCEL_COMPARISON_APP_DATA = 'CANCEL_COMPARISON_APP_DATA';

export const REQUEST_COMPARISON_DIFF_APP_DATA =
  'REQUEST_COMPARISON_DIFF_APP_DATA';
export const RECEIVE_COMPARISON_DIFF_APP_DATA =
  'RECEIVE_COMPARISON_DIFF_APP_DATA';
export const CANCEL_COMPARISON_DIFF_APP_DATA =
  'CANCEL_COMPARISON_DIFF_APP_DATA';

export const REQUEST_NAMES = 'REQUEST_NAMES';
export const RECEIVE_NAMES = 'RECEIVE_NAMES';
export const SET_LEFT_FROM = 'SET_LEFT_FROM';
export const SET_LEFT_UNTIL = 'SET_LEFT_UNTIL';
export const SET_RIGHT_FROM = 'SET_RIGHT_FROM';
export const SET_RIGHT_UNTIL = 'SET_RIGHT_UNTIL';
export const SET_LEFT_DATE_RANGE = 'SET_LEFT_DATE_RANGE';
export const SET_RIGHT_DATE_RANGE = 'SET_RIGHT_DATE_RANGE';
export const REQUEST_TAGS = 'REQUEST_TAGS';
export const RECEIVE_TAGS = 'RECEIVE_TAGS';
export const REQUEST_TAG_VALUES = 'REQUEST_TAG_VALUES';
export const RECEIVE_TAG_VALUES = 'RECEIVE_TAG_VALUES';
export const REQUEST_COMPARISON_TIMELINE = 'REQUEST_COMPARISON_TIMELINE';
export const RECEIVE_COMPARISON_TIMELINE = 'RECEIVE_COMPARISON_TIMELINE';
export const SET_ADHOC_FILE = 'SET_ADHOC_FILE';
export const SET_ADHOC_LEFT_FILE = 'SET_ADHOC_LEFT_FILE';
export const SET_ADHOC_RIGHT_FILE = 'SET_ADHOC_RIGHT_FILE';
export const REQUEST_ADHOC_PROFILES = 'REQUEST_ADHOC_PROFILES';
export const RECEIVE_ADHOC_PROFILES = 'RECEIVE_ADHOC_PROFILES';
export const SET_ADHOC_PROFILE = 'SET_ADHOC_PROFILE';
export const REQUEST_ADHOC_PROFILE = 'REQUEST_ADHOC_PROFILE';
export const RECEIVE_ADHOC_PROFILE = 'RECEIVE_ADHOC_PROFILE';
export const SET_ADHOC_LEFT_PROFILE = 'SET_ADHOC_LEFT_PROFILE';
export const SET_ADHOC_RIGHT_PROFILE = 'SET_ADHOC_RIGHT_PROFILE';
export const REQUEST_ADHOC_LEFT_PROFILE = 'REQUEST_ADHOC_LEFT_PROFILE';
export const REQUEST_ADHOC_RIGHT_PROFILE = 'REQUEST_ADHOC_RIGHT_PROFILE';
export const RECEIVE_ADHOC_LEFT_PROFILE = 'RECEIVE_ADHOC_LEFT_PROFILE';
export const RECEIVE_ADHOC_RIGHT_PROFILE = 'RECEIVE_ADHOC_RIGHT_PROFILE';
