export const REQUEST_ADHOC_PROFILES = 'REQUEST_ADHOC_PROFILES';
export const RECEIVE_ADHOC_PROFILES = 'RECEIVE_ADHOC_PROFILES';
export const CANCEL_ADHOC_PROFILES = 'CANCEL_ADHOC_PROFILES';

export const SET_ADHOC_FILE = 'SET_ADHOC_FILE';
export const SET_ADHOC_LEFT_FILE = 'SET_ADHOC_LEFT_FILE';
export const SET_ADHOC_RIGHT_FILE = 'SET_ADHOC_RIGHT_FILE';

export const SET_ADHOC_PROFILE = 'SET_ADHOC_PROFILE';
export const REQUEST_ADHOC_PROFILE = 'REQUEST_ADHOC_PROFILE';
export const RECEIVE_ADHOC_PROFILE = 'RECEIVE_ADHOC_PROFILE';
export const CANCEL_ADHOC_PROFILE = 'CANCEL_ADHOC_PROFILE';

export const SET_ADHOC_LEFT_PROFILE = 'SET_ADHOC_LEFT_PROFILE';
export const SET_ADHOC_RIGHT_PROFILE = 'SET_ADHOC_RIGHT_PROFILE';
export const REQUEST_ADHOC_LEFT_PROFILE = 'REQUEST_ADHOC_LEFT_PROFILE';
export const REQUEST_ADHOC_RIGHT_PROFILE = 'REQUEST_ADHOC_RIGHT_PROFILE';
export const RECEIVE_ADHOC_LEFT_PROFILE = 'RECEIVE_ADHOC_LEFT_PROFILE';
export const RECEIVE_ADHOC_RIGHT_PROFILE = 'RECEIVE_ADHOC_RIGHT_PROFILE';
export const CANCEL_ADHOC_LEFT_PROFILE = 'CANCEL_ADHOC_LEFT_PROFILE';
export const CANCEL_ADHOC_RIGHT_PROFILE = 'RECEIVE_ADHOC_RIGHT_PROFILE';

export const REQUEST_ADHOC_PROFILE_DIFF = 'REQUEST_ADHOC_PROFILE_DIFF';
export const RECEIVE_ADHOC_PROFILE_DIFF = 'RECEIVE_ADHOC_PROFILE_DIFF';
export const CANCEL_ADHOC_PROFILE_DIFF = 'CANCEL_ADHOC_PROFILE_DIFF';
