{
 "title": "Pyroscope / Operational",
 "description": "Bird eyes view of Pyroscope clusters",
 "tags": [ "pyroscope" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "loki_datasource", "query": "loki" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(pyroscope_build_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(pyroscope_build_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MBs per Tenant (Decompressed)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (tenant) (rate(pyroscope_distributor_received_decompressed_bytes_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Profiles/s per Tenant",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (tenant) (rate(pyroscope_distributor_received_decompressed_bytes_count{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[10m]) > 0",
     "legendFormat": "{{container}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Ingester Ring Status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state) (pyroscope_ring_members{cluster=~\"$cluster\", namespace=~\"$namespace\", name=\"ingester\"}) / count by (state)(pyroscope_ring_members{cluster=~\"$cluster\", namespace=~\"$namespace\", name=\"ingester\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distributor Ring Status",
   "type": "piechart",
   "description": "Distributor Ring is used for rate limiting",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state) (pyroscope_ring_members{cluster=~\"$cluster\", namespace=~\"$namespace\", name=\"distributor\"}) / count by (state)(pyroscope_ring_members{cluster=~\"$cluster\", namespace=~\"$namespace\", name=\"distributor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tenant id / name mapping",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "\nsum by (tenant, slug, org_name, environment) (\n  rate(pyroscope_distributor_received_decompressed_bytes_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pushes/Second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status) (\nlabel_replace(\n  label_replace(\n        rate(pyroscope_request_duration_seconds_count{cluster=~\"$cluster\", container=~\"pyroscope|distributor|query-frontend\", namespace=~\"$namespace\", route=~\".*ingest.*|.*pusher.*\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n\"status\", \"${1}\", \"status_code\", \"([a-z]+)\")\n)",
     "legendFormat": "{{status}} "
    }
   ]
  },
  {
   "title": "Push Latencies",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, route) ( rate(pyroscope_request_duration_seconds_bucket{container=~\"pyroscope|distributor|query-frontend\", namespace=~\"$namespace\", cluster=~\"$cluster\",route=~\".*ingest.*|.*pusher.*\"}[$__rate_interval])))",
     "legendFormat": ".99 {{route}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le, route) ( rate(pyroscope_request_duration_seconds_bucket{container=~\"pyroscope|distributor|query-frontend\", namespace=~\"$namespace\", cluster=~\"$cluster\",route=~\".*ingest.*|.*pusher.*\"}[$__rate_interval])))",
     "legendFormat": ".75 {{route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le, route) ( rate(pyroscope_request_duration_seconds_bucket{container=~\"pyroscope|distributor|query-frontend\", namespace=~\"$namespace\", cluster=~\"$cluster\",route=~\".*ingest.*|.*pusher.*\"}[$__rate_interval])))",
     "legendFormat": ".5 {{route}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "count by (container,version) (pyroscope_build_info{cluster=~\"$cluster\",namespace=~\"$namespace\"}) or count by (container,version) (cloud_backend_gateway_build_info{cluster=~\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Queries/Second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status) (\nlabel_replace(\n  label_replace(\n        rate(pyroscope_request_duration_seconds_count{cluster=~\"$cluster\", container=~\"pyroscope|distributor|query-frontend\", namespace=~\"$namespace\", route=~\".*pyroscope_render.*|.*pyroscope_label.*|.*querierservice.*\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n\"status\", \"${1}\", \"status_code\", \"([a-z]+)\")\n)",
     "legendFormat": "{{status}} "
    }
   ]
  },
  {
   "title": "Query Latencies",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, route) ( rate(pyroscope_request_duration_seconds_bucket{container=~\"pyroscope|distributor|query-frontend\", namespace=~\"$namespace\", cluster=~\"$cluster\",route=~\".*pyroscope_render.*|.*pyroscope_label.*|.*querierservice.*\"}[$__rate_interval])))",
     "legendFormat": ".99 {{route}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le, route) ( rate(pyroscope_request_duration_seconds_bucket{container=~\"pyroscope|distributor|query-frontend\", namespace=~\"$namespace\", cluster=~\"$cluster\",route=~\".*pyroscope_render.*|.*pyroscope_label.*|.*querierservice.*\"}[$__rate_interval])))",
     "legendFormat": ".75 {{route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le, route) ( rate(pyroscope_request_duration_seconds_bucket{container=~\"pyroscope|distributor|query-frontend\", namespace=~\"$namespace\", cluster=~\"$cluster\",route=~\".*pyroscope_render.*|.*pyroscope_label.*|.*querierservice.*\"}[$__rate_interval])))",
     "legendFormat": ".5 {{route}}"
    }
   ]
  },
  {
   "title": "Error & Panic rate",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (container)( count_over_time({namespace=~\"$namespace\",cluster=~\"$cluster\"} != \"stream context finished\" != \"fast-joining node failed\" != \"CAS attempt failed\" != \"memberlist TCPTransport\" |= \" panic \" or \"panic:\" or \" err=\" or \"level=error\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Errors and Panics",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\",cluster=~\"$cluster\"} != \"stream context finished\" != \"fast-joining node failed\" != \"CAS attempt failed\" != \"memberlist TCPTransport\" |= \" panic \" or \"panic:\" or \" err=\" or \"level=error\""
    }
   ]
  },
  {
   "title": "Query Activity",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=~\"$namespace\", cluster=~\"$cluster\", container=\"cortex-gw\"} |= `msg=\"request timings\"` | logfmt"
    }
   ]
  },
  {
   "title": "Ingesters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\", namespace=~\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*ingester\", workload_type=\"statefulset\"}\n) by (pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*ingester\", workload_type=\"statefulset\"}\n)",
       "legendFormat": "request"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*ingester\", workload_type=\"statefulset\"}\n)",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\n    container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*ingester\", workload_type=\"statefulset\"}\n) by (pod)\n",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*ingester\", workload_type=\"statefulset\"}\n)",
       "legendFormat": "request"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*ingester\", workload_type=\"statefulset\"}\n)",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum(irate(container_network_receive_bytes_total{job=~\"(.*/)?cadvisor\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*ingester.*\", workload_type=\"statefulset\"}) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum(irate(container_network_transmit_bytes_total{job=~\"(.*/)?cadvisor\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*ingester.*\", workload_type=\"statefulset\"}) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Push Latencies",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le, route) ( rate(pyroscope_request_duration_seconds_bucket{job=~\"$namespace/ingester\", cluster=~\"$cluster\",route=~\".*push.*\"}[$__rate_interval])))",
       "legendFormat": ".99 {{route}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum by (le, route) ( rate(pyroscope_request_duration_seconds_bucket{job=~\"$namespace/ingester\", cluster=~\"$cluster\",route=~\".*push.*\"}[$__rate_interval])))",
       "legendFormat": ".75 {{route}}"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le, route) ( rate(pyroscope_request_duration_seconds_bucket{job=~\"$namespace/ingester\", cluster=~\"$cluster\",route=~\".*push.*\"}[$__rate_interval])))",
       "legendFormat": ".5 {{route}}"
      }
     ]
    },
    {
     "title": "Pushes/Second",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (status) (\nlabel_replace(\n  label_replace(\n        rate(pyroscope_request_duration_seconds_count{cluster=~\"$cluster\", job=~\"$namespace/ingester\", route=~\".*push.*\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n\"status\", \"${1}\", \"status_code\", \"([a-z]+)\")\n)",
       "legendFormat": "{{status}} "
      }
     ]
    },
    {
     "title": "Block Uploaded Per Tenant",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum by (tenant) (count_over_time({cluster=~\"$cluster\",namespace=~\"$namespace\"} |= \"upload new block\" | logfmt [$__interval]))"
      }
     ]
    },
    {
     "title": "Profiles Flushed to disk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum by (tenant) (sum_over_time({cluster=~\"$cluster\",namespace=~\"$namespace\"} |= \"cut row group segment\" | logfmt | unwrap numProfiles [$__interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Tenant Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Discarded Profiles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "topk(10,sum by (tenant, reason) (rate(pyroscope_discarded_samples_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[1m])))",
       "legendFormat": "{{ tenant }} - {{ reason }}"
      }
     ]
    },
    {
     "title": "Discarded Profiles Per Interval",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "topk(10, sum by (tenant, reason) (sum_over_time(increase(pyroscope_discarded_samples_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[1m])[$__range:1m])))",
       "legendFormat": "{{ tenant }} - {{ reason }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distributors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\", namespace=~\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*distributor\", workload_type=\"deployment\"}\n) by (pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*distributor\", workload_type=\"deployment\"}\n)",
       "legendFormat": "request"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*distributor\", workload_type=\"deployment\"}\n)",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\n    container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*distributor\", workload_type=\"deployment\"}\n) by (pod)\n",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*distributor\", workload_type=\"deployment\"}\n)",
       "legendFormat": "request"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*distributor\", workload_type=\"deployment\"}\n)",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum(irate(container_network_receive_bytes_total{job=~\"(.*/)?cadvisor\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*distributor.*\", workload_type=\"deployment\"}) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum(irate(container_network_transmit_bytes_total{job=~\"(.*/)?cadvisor\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*distributor.*\", workload_type=\"deployment\"}) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Profiles /s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum by (type) (rate(pyroscope_distributor_received_compressed_bytes_count{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Stacktrace Sample /s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "sum by (type) (rate(pyroscope_distributor_received_samples_sum{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Throughput Decompressed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (type) (rate(pyroscope_distributor_received_decompressed_bytes_sum{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Throughput Samples Decompressed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (type) (rate(pyroscope_distributor_received_samples_bytes_sum{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Throughput Symbols Decompressed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (type) (rate(pyroscope_distributor_received_symbols_bytes_sum{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Latencies",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le, route) ( rate(pyroscope_request_duration_seconds_bucket{job=~\"$namespace/query-frontend\", cluster=~\"$cluster\",route=~\".*render.*|.*querier.*\"}[$__rate_interval])))",
       "legendFormat": ".99 {{route}}"
      }
     ]
    },
    {
     "title": "Request Rates",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (status,route) (\nlabel_replace(\n  label_replace(\n        rate(pyroscope_request_duration_seconds_count{cluster=~\"$cluster\", job=~\"$namespace/query-frontend\", route=~\".*render.*|.*querier.*\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n\"status\", \"${1}\", \"status_code\", \"([a-z]+)\")\n)",
       "legendFormat": "{{status}}  {{route}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\", namespace=~\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*query-frontend\", workload_type=\"deployment\"}\n) by (pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*query-frontend\", workload_type=\"deployment\"}\n)",
       "legendFormat": "request"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*query-frontend\", workload_type=\"deployment\"}\n)",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\n    container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*query-frontend\", workload_type=\"deployment\"}\n) by (pod)\n",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*query-frontend\", workload_type=\"deployment\"}\n)",
       "legendFormat": "request"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*query-frontend\", workload_type=\"deployment\"}\n)",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum(irate(container_network_receive_bytes_total{job=~\"(.*/)?cadvisor\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*query-frontend.*\", workload_type=\"deployment\"}) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum(irate(container_network_transmit_bytes_total{job=~\"(.*/)?cadvisor\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*query-frontend.*\", workload_type=\"deployment\"}) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Queries",
     "type": "logs",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\",cluster=~\"$cluster\",container=\"query-frontend\"} |= \"http.go\" |~ \"QuerierService|pyroscope|render\" | logfmt | line_format \"tenant={{.orgID}} traceID={{.traceID}} {{.msg}}\""
      }
     ]
    }
   ]
  },
  {
   "title": "Queriers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\", namespace=~\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*querier\", workload_type=\"deployment\"}\n) by (pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*querier\", workload_type=\"deployment\"}\n)",
       "legendFormat": "request"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*querier\", workload_type=\"deployment\"}\n)",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\n    container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*querier\", workload_type=\"deployment\"}\n) by (pod)\n",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*querier\", workload_type=\"deployment\"}\n)",
       "legendFormat": "request"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*querier\", workload_type=\"deployment\"}\n)",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum(irate(container_network_receive_bytes_total{job=~\"(.*/)?cadvisor\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*querier.*\", workload_type=\"deployment\"}) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum(irate(container_network_transmit_bytes_total{job=~\"(.*/)?cadvisor\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*querier.*\", workload_type=\"deployment\"}) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\", namespace=~\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*query-scheduler\", workload_type=\"deployment\"}\n) by (pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*query-scheduler\", workload_type=\"deployment\"}\n)",
       "legendFormat": "request"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*query-scheduler\", workload_type=\"deployment\"}\n)",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\n    container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*query-scheduler\", workload_type=\"deployment\"}\n) by (pod)\n",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*query-scheduler\", workload_type=\"deployment\"}\n)",
       "legendFormat": "request"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*query-scheduler\", workload_type=\"deployment\"}\n)",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Store Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Latencies",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le, route) ( rate(pyroscope_request_duration_seconds_bucket{job=~\"$namespace/store-gateway\", cluster=~\"$cluster\",route=~\".*store.*\"}[$__rate_interval])))",
       "legendFormat": ".99 {{route}}"
      }
     ]
    },
    {
     "title": "Request Rates",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (status,route) (\nlabel_replace(\n  label_replace(\n        rate(pyroscope_request_duration_seconds_count{cluster=~\"$cluster\", job=~\"$namespace/store-gateway\", route=~\".*store.*\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n\"status\", \"${1}\", \"status_code\", \"([a-z]+)\")\n)",
       "legendFormat": "{{status}}  {{route}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\", namespace=~\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*store-gateway\", workload_type=\"statefulset\"}\n) by (pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*store-gateway\", workload_type=\"statefulset\"}\n)",
       "legendFormat": "request"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*store-gateway\", workload_type=\"statefulset\"}\n)",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\n    container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*store-gateway\", workload_type=\"statefulset\"}\n) by (pod)\n",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*store-gateway\", workload_type=\"statefulset\"}\n)",
       "legendFormat": "request"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=~\"(.*/)?kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*store-gateway\", workload_type=\"statefulset\"}\n)",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum(irate(container_network_receive_bytes_total{job=~\"(.*/)?cadvisor\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*store-gateway.*\", workload_type=\"statefulset\"}) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum(irate(container_network_transmit_bytes_total{job=~\"(.*/)?cadvisor\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*store-gateway.*\", workload_type=\"statefulset\"}) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Object Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bucket Operation /s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "sum by(operation)  (rate(objstore_bucket_operations_total{namespace=~\"$namespace\",cluster=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latencies per Operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(objstore_bucket_operation_duration_seconds{namespace=~\"$namespace\",cluster=~\"$cluster\"}[$__rate_interval])) by (operation))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "GitHub API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "GitHub API (P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, route) (rate(pyroscope_vcs_github_request_duration_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"querier\"} [$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GitHub API (P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (route, status_code) (rate(pyroscope_vcs_github_request_duration_count{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"querier\"} [$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}