{
 "title": "Pyroscope v2 / Metastore",
 "tags": [
  "pyroscope",
  "pyroscope-v2"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "loki_datasource", "query": "loki" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(pyroscope_build_info{namespace=\"$namespace\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(pyroscope_build_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Raft", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Raft Nodes",
   "type": "state-timeline",
   "description": "Raft node roles observed by each node. The view is not meant to be 100% consistent, and only serves monitoring purposes",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  pyroscope_metastore_raft_state{namespace=\"$namespace\",state=\"Follower\"} or\n  pyroscope_metastore_raft_state{namespace=\"$namespace\",state=\"Leader\"} * 100\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Command Latency",
   "type": "timeseries",
   "description": "The latency of raft commands observed by the metastore leader",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.995, sum(rate(pyroscope_metastore_raft_apply_command_duration_seconds_bucket{\n  namespace=\"$namespace\",\n}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "ReadIndex Latency",
   "type": "timeseries",
   "description": "The latency of raft read index observed by the metastore nodes",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(pyroscope_metastore_raft_read_index_wait_duration_seconds_bucket{\n  namespace=\"$namespace\",\n}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Snapshot Latency",
   "type": "timeseries",
   "description": "The time takes to write a snapshot",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\n  histogram_quantile(0.99,(sum by (le, pod) (\n    irate(pyroscope_metastore_boltdb_persist_snapshot_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))\n  ) * on(pod) group_left() (pyroscope_metastore_raft_state{namespace=\"$namespace\", state=\"Leader\"} >= 1)\n)",
     "legendFormat": "{{pod}} Leader"
    },
    {
     "expr": "(\n  histogram_quantile(0.99,(sum by (le, pod) (\n    irate(pyroscope_metastore_boltdb_persist_snapshot_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))\n  ) * on(pod) group_left() (pyroscope_metastore_raft_state{namespace=\"$namespace\", state!=\"Leader\"} >= 1)\n)",
     "legendFormat": "{{pod}} Follower"
    }
   ]
  },
  {
   "title": "Snapshot Size",
   "type": "timeseries",
   "description": "The size of BoltDB snapshot taken by FSM",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pyroscope_metastore_boltdb_persist_snapshot_size_bytes{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "FSM Latency",
   "type": "timeseries",
   "description": "The time takes to apply the command onto FSM",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(pyroscope_metastore_fsm_apply_command_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(pyroscope_metastore_fsm_apply_command_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  { "title": "Metadata Index Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "AddBlock Latency",
   "type": "timeseries",
   "description": "The latency of AddBlock endpoint observed by metastore nodes\n\nThe only user is the segment-writer service.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\n  histogram_quantile(1,(sum by (le, pod) (\n    irate(pyroscope_metastore_boltdb_persist_snapshot_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))\n  ) * on(pod) group_left() (pyroscope_metastore_raft_state{namespace=\"$namespace\", state=\"Leader\"} >= 1)\n)",
     "legendFormat": "Metastore leader snapshot ({{pod}})"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(pyroscope_request_duration_seconds_bucket{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.IndexService/AddBlock\",\n}[$__rate_interval])) by (le, pod))",
     "legendFormat": "p99 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(pyroscope_request_duration_seconds_bucket{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.IndexService/AddBlock\",\n}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(pyroscope_request_duration_seconds{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.IndexService/AddBlock\",\n}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(pyroscope_request_duration_seconds_count{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.IndexService/AddBlock\",\n}[$__rate_interval])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GetBlockMetadata Latency",
   "type": "timeseries",
   "description": "The latency of GetBlockMetadata endpoint observed by metastore nodes.\n\nThe only user is the compaction-worker service.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(pyroscope_request_duration_seconds_bucket{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.IndexService/GetBlockMetadata\",\n}[$__rate_interval])) by (le, pod))",
     "legendFormat": "p99 {{pod}}"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(pyroscope_request_duration_seconds{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.IndexService/GetBlockMetadata\"\n}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(pyroscope_request_duration_seconds_count{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.IndexService/GetBlockMetadata\",\n}[$__rate_interval])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Metadata Query Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "QueryMetadata Latency",
   "type": "timeseries",
   "description": "The latency of QueryMetadata endpoint observed by metastore nodes.\n\nThe only user is the query-frontend service.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(pyroscope_request_duration_seconds_bucket{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.MetadataQueryService/QueryMetadata\",\n}[$__rate_interval])) by (le, pod))",
     "legendFormat": "p99 {{pod}}"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(pyroscope_request_duration_seconds{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.MetadataQueryService/QueryMetadata\",\n}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(pyroscope_request_duration_seconds_count{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.MetadataQueryService/QueryMetadata\",\n}[$__rate_interval])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QueryMetadataLabels Latency",
   "type": "timeseries",
   "description": "The latency of QueryMetadataLabels endpoint observed by metastore nodes.\n\nThe only user is the query-frontend service.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(pyroscope_request_duration_seconds_bucket{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.MetadataQueryService/QueryMetadataLabels\",\n}[$__rate_interval])) by (le, pod))",
     "legendFormat": "p99 {{pod}}"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(pyroscope_request_duration_seconds{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.MetadataQueryService/QueryMetadataLabels\",\n}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(pyroscope_request_duration_seconds_count{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.MetadataQueryService/QueryMetadataLabels\",\n}[$__rate_interval])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Compaction Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "PollCompactionJobs Latency",
   "type": "timeseries",
   "description": "The latency of PollCompactionJobs endpoint observed by metastore nodes.\n\nThe only user is the compaction-worker service.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(pyroscope_request_duration_seconds_bucket{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.CompactionService/PollCompactionJobs\",\n}[$__rate_interval])) by (le, pod))",
     "legendFormat": "p99 {{pod}}"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(pyroscope_request_duration_seconds{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.CompactionService/PollCompactionJobs\",\n}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(pyroscope_request_duration_seconds_count{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.CompactionService/PollCompactionJobs\",\n}[$__rate_interval])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\",container=\"metastore\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"metastore\", image!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=\"$namespace\",persistentvolumeclaim=~\".*metastore.*\"} /\nkubelet_volume_stats_capacity_bytes{namespace=\"$namespace\",persistentvolumeclaim=~\".*metastore.*\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Storage I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(operation) (rate(objstore_bucket_operations_total{namespace=\"$namespace\",container=\"metastore\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total{job=~\"(.*/)?cadvisor\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]) * on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*metastore.*\"}) by (namespace,pod)) * -1",
     "legendFormat": "tx {{pod}}"
    },
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{job=~\"(.*/)?cadvisor\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]) * on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*metastore.*\"}) by (namespace,pod))",
     "legendFormat": "rx {{pod}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_fs_writes_total{namespace=\"$namespace\",container=\"metastore\"}[$__rate_interval])) * -1",
     "legendFormat": "write {{pod}}"
    },
    {
     "expr": "sum by (pod) (irate(container_fs_reads_total{namespace=\"$namespace\",container=\"metastore\"}[$__rate_interval]))",
     "legendFormat": "read {{pod}}"
    }
   ]
  },
  {
   "title": "Disk I/O Wait",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 69 },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{cluster=\"$cluster\"}[$__rate_interval])\n+ on(instance, device) group_left(pod)\ntopk by(instance, device) (\n  1,\n  0 * label_replace(\n    container_blkio_device_usage_total{\n      cluster=\"$cluster\",\n      namespace=\"$namespace\",\n      container=\"metastore\",\n      operation=\"Write\",\n    },\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  )\n)\n",
     "legendFormat": "{{pod}}/{{device}}"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go Threads",
     "type": "timeseries",
     "description": "Number of OS threads created",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_threads{namespace=\"$namespace\",container=\"metastore\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (go_goroutines{namespace=\"$namespace\",container=\"metastore\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap In-Use",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (go_memstats_heap_inuse_bytes{namespace=\"$namespace\",container=\"metastore\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 113 },
     "targets": [
      {
       "expr": "sum by (pod) (container_file_descriptors{namespace=\"$namespace\",container=\"metastore\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}