{
 "title": "Pyroscope v2 / Write Path",
 "tags": [
  "pyroscope",
  "pyroscope-v2"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "loki_datasource", "query": "loki" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(pyroscope_build_info{namespace=\"$namespace\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(pyroscope_build_info,namespace)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tenants",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "\nsum by (tenant, slug, org_name, environment) (\n  rate(pyroscope_distributor_received_decompressed_bytes_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MBs per Tenant (Decompressed)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (tenant) (rate(pyroscope_distributor_received_decompressed_bytes_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Profiles/s per Tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (tenant) (rate(pyroscope_distributor_received_decompressed_bytes_count{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distributor Ring",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state) (pyroscope_ring_members{cluster=~\"$cluster\", namespace=~\"$namespace\", name=\"distributor\"}) / count by (state)(pyroscope_ring_members{cluster=~\"$cluster\", namespace=~\"$namespace\", name=\"distributor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segment Writer Ring",
   "type": "piechart",
   "description": "The ring is used by distributor to discover segment-writer instances. ",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state) (pyroscope_ring_members{cluster=~\"$cluster\", namespace=~\"$namespace\", name=\"segment-writer\"}) / count by (state)(pyroscope_ring_members{cluster=~\"$cluster\", namespace=~\"$namespace\", name=\"segment-writer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distributor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "timeseries",
     "description": "The latency observed by distributor, indicating the overall write path latency.\n\nOnly successful requests are counted.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le, pod) (rate(pyroscope_request_duration_seconds_bucket{\n    namespace=\"$namespace\",\n    container=\"distributor\",\n    route=~\".*pusher.*|.*ingest.*\",\n    status_code=\"200\",\n}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "targets": [
      {
       "expr": "sum(rate(pyroscope_request_duration_seconds{\n    namespace=\"$namespace\",\n    container=\"distributor\",\n    route=~\".*push.*|.*ingest.*\",\n}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (status_code) (rate(\n    pyroscope_request_duration_seconds_count{\n        namespace=\"$namespace\",\n        container=\"distributor\",\n        route=~\".*push.*|.*ingest.*\",\n    }[1m])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Downstream Latency",
     "type": "timeseries",
     "description": "The latency observed by distributors (write path router), broken down by instance.\n\nLatencies are expected to be distributed evenly across instances. An outlier here likely indicates a neighborhood issue.\n\nOnly successful requests are counted.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pyroscope_write_path_downstream_request_duration_seconds_bucket{\n    namespace=\"$namespace\",\n    status=\"200\",\n    primary=\"1\",\n}[$__rate_interval])) by (le, route,pod))",
       "legendFormat": "p99 primary {{pod}} => {{route}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pyroscope_write_path_downstream_request_duration_seconds_bucket{\n    namespace=\"$namespace\",\n    status=\"200\",\n    primary!=\"1\",\n}[$__rate_interval])) by (le, route,pod))",
       "legendFormat": "p99 secondary {{pod}} => {{route}}"
      }
     ]
    },
    {
     "title": "Latency Heatmap",
     "type": "heatmap",
     "description": "The latency observed by the segment-writer client",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
     "targets": [
      {
       "expr": "sum(rate(pyroscope_write_path_downstream_request_duration_seconds{\n    namespace=\"$namespace\",\n    route=\"segment-writer\",\n}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Downstream Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(pyroscope_write_path_downstream_request_duration_seconds_count{\n    namespace=\"$namespace\",\n    primary=\"1\",\n}[$__rate_interval])) by (status,route)",
       "legendFormat": "primary {{route}} {{status}}"
      },
      {
       "expr": "sum(irate(pyroscope_write_path_downstream_request_duration_seconds_count{\n    namespace=\"$namespace\",\n    primary=\"0\",\n}[$__rate_interval])) by (status,route)",
       "legendFormat": "secondary {{route}} {{status}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"$namespace\",container=\"distributor\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{job=~\"(.*/)?kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\", container=\"distributor\"})",
       "legendFormat": "Request"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
     "targets": [
      {
       "expr": "sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\",container=\"distributor\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(\n    kube_pod_container_resource_requests{job=~\"(.*/)?kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\".*-distributor\"}\n)",
       "legendFormat": "Request"
      },
      {
       "expr": "max(\n    kube_pod_container_resource_limits{job=~\"(.*/)?kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\".*-distributor\"}\n)",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Upstream Distribution",
     "type": "timeseries",
     "description": "The chart showd distribution of requests from the upstream (cortex-gw/envoy)",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(\n    pyroscope_request_duration_seconds_count{\n        namespace=\"$namespace\",\n        container=\"distributor\",\n        route=~\".*push.*|.*ingest.*\",\n    }[1m])\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Segment Writer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Push Latency",
   "type": "timeseries",
   "description": "The latency of the Push endpoint observed by segment-writer.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(pyroscope_request_duration_seconds_bucket{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  # status_code=\"success\",\n  route=\"/segmentwriter.v1.SegmentWriterService/Push\",\n}[$__rate_interval])) by (le, pod))",
     "legendFormat": "p99 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(pyroscope_request_duration_seconds_bucket{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  # status_code=\"success\",\n  route=\"/segmentwriter.v1.SegmentWriterService/Push\",\n}[$__rate_interval])) by (le))",
     "legendFormat": "p99 overall"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(pyroscope_request_duration_seconds_bucket{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  # status_code=\"success\",\n  route=\"/segmentwriter.v1.SegmentWriterService/Push\",\n}[$__rate_interval])) by (le))",
     "legendFormat": "p90 overall"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(pyroscope_request_duration_seconds_bucket{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  # status_code=\"success\",\n  route=\"/segmentwriter.v1.SegmentWriterService/Push\",\n}[$__rate_interval])) by (le))",
     "legendFormat": "p50 overall"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "description": "The latency of the Push endpoint observed by segment-writer",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(pyroscope_request_duration_seconds{\n  namespace=\"$namespace\",\n  container=\"segment-writer\",\n  method=\"gRPC\",\n  # status_code=\"success\",\n  route=\"/segmentwriter.v1.SegmentWriterService/Push\",\n}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Push Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(pyroscope_request_duration_seconds_count{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/segmentwriter.v1.SegmentWriterService/Push\",\n}[$__rate_interval])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Object Store Upload Latency",
   "type": "timeseries",
   "description": "The latency segment-writer observes when uploading segments to object store, including retries.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(pyroscope_segment_writer_upload_duration_seconds_bucket{namespace=\"$namespace\",container=\"segment-writer\"}[$__rate_interval])) by (le, pod))",
     "legendFormat": "p99 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(pyroscope_segment_writer_upload_duration_seconds_bucket{namespace=\"$namespace\",container=\"segment-writer\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99 overall"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(pyroscope_segment_writer_upload_duration_seconds_bucket{namespace=\"$namespace\",container=\"segment-writer\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90 overall"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(pyroscope_segment_writer_upload_duration_seconds_bucket{namespace=\"$namespace\",container=\"segment-writer\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50 overall"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "description": "The latency of upload calls observed by the segment-writer",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(pyroscope_segment_writer_upload_duration_seconds{namespace=\"$namespace\",container=\"segment-writer\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Object Store Upload Rate",
   "type": "timeseries",
   "description": "New objects created by segment-writer",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(pyroscope_segment_writer_upload_duration_seconds_count{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (status) (rate(pyroscope_segment_writer_hedged_upload_duration_seconds_count{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{status}} (hedged)"
    }
   ]
  },
  {
   "title": "Store Metadata Latency",
   "type": "timeseries",
   "description": "The latency segment-writer observes when adding metadata entries to metastore, including retries.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(pyroscope_segment_writer_store_metadata_duration_seconds_bucket{namespace=\"$namespace\",container=\"segment-writer\"}[$__rate_interval])) by (le, pod))",
     "legendFormat": "p99 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(pyroscope_segment_writer_store_metadata_duration_seconds_bucket{namespace=\"$namespace\",container=\"segment-writer\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99 overall"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(pyroscope_segment_writer_store_metadata_duration_seconds_bucket{namespace=\"$namespace\",container=\"segment-writer\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90 overall"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(pyroscope_segment_writer_store_metadata_duration_seconds_bucket{namespace=\"$namespace\",container=\"segment-writer\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50 overall"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "description": "The latency segment-writer observes when adding metadata entries, including retries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(pyroscope_segment_writer_store_metadata_duration_seconds{namespace=\"$namespace\",container=\"segment-writer\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Store Metadata Rate",
   "type": "timeseries",
   "description": "New metadata entries created by segment-writers",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(pyroscope_segment_writer_store_metadata_duration_seconds_count{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (status) (rate(pyroscope_segment_writer_store_metadata_dql{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{status}} (DLQ)"
    },
    {
     "expr": "sum(rate(pyroscope_segment_writer_store_metadata_dlq{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "dlq"
    }
   ]
  },
  {
   "title": "Processing Rate (MB/sec/core)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (irate(pyroscope_segment_writer_received_decompressed_bytes_sum{namespace=\"$namespace\", container=\"segment-writer\"}[10m])) /\nsum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"segment-writer\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"segment-writer\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_requests{job=~\"(.*/)?kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\".*-segment-writer\"}\n)",
     "legendFormat": "Request"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_limits{job=~\"(.*/)?kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\".*-segment-writer\"}\n)",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU Usage (stack)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"segment-writer\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"segment-writer\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Metastore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raft Nodes",
     "type": "state-timeline",
     "description": "The latency of raft commands observed by the metastore leader",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  pyroscope_metastore_raft_state{namespace=\"$namespace\",state=\"Follower\"} or\n  pyroscope_metastore_raft_state{namespace=\"$namespace\",state=\"Leader\"} * 100\n)",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "description": "The latency of AddBlock endpoint observed by metastore nodes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(\n  histogram_quantile(0.99,(sum by (le, pod) (\n    irate(pyroscope_metastore_boltdb_persist_snapshot_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))\n  ) * on(pod) group_left() (pyroscope_metastore_raft_state{namespace=\"$namespace\", state=\"Leader\"} >= 1)\n)",
       "legendFormat": "Metastore leader snapshot ({{pod}})"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pyroscope_request_duration_seconds_bucket{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.IndexService/AddBlock\",\n}[$__rate_interval])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(pyroscope_request_duration_seconds_bucket{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.IndexService/AddBlock\",\n}[$__rate_interval])) by (le))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(pyroscope_request_duration_seconds_count{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  container=\"metastore\",\n  route=\"/metastore.v1.IndexService/AddBlock\",\n}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dataset Shards",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 17, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "sum by (dataset, tenant) (\n    pyroscope_adaptive_placement_dataset_shard_limit{namespace=\"$namespace\"}\n) > 1",
       "legendFormat": "{{tenant}}/{{dataset}}"
      }
     ]
    },
    {
     "title": "Datasets per tenant",
     "type": "timeseries",
     "description": "Top-10",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 69 },
     "targets": [
      {
       "expr": "topk(10, count by (tenant) (sum by (dataset, tenant) (\n    pyroscope_adaptive_placement_dataset_shard_limit{namespace=\"$namespace\"}\n)))",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "Distributed Bytes (per shard)",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "sum by (shard) (rate(pyroscope_segment_writer_client_sent_bytes_sum{namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Distributed Bytes (per shard)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (shard) (rate(pyroscope_segment_writer_client_sent_bytes_sum{namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Distributed Bytes (per shard, stack)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (shard) (rate(pyroscope_segment_writer_client_sent_bytes_sum{namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ingested Bytes (per node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(pyroscope_segment_writer_received_decompressed_bytes_sum{namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ingested Bytes (per node, stack)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(pyroscope_segment_writer_received_decompressed_bytes_sum{namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Ingested Profiles (per node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(pyroscope_segment_writer_received_decompressed_bytes_count{namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ingested Profiles (per node, stack)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(pyroscope_segment_writer_received_decompressed_bytes_count{namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Allocation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "AWS | Intances By Machine Type",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 168 },
     "targets": [
      {
       "expr": "count by (instance_type, container) (\n    rate(container_cpu_usage_seconds_total{\n        cluster=\"$cluster\",\n        namespace=\"$namespace\",\n        container=~\"segment-writer|distributor|cortex-gw|metastore|compaction-worker\",\n    }[$__rate_interval]) + on (instance) group_left(instance_type) (0 * label_replace(\n        karpenter_nodes_allocatable{cluster=\"$cluster\", resource_type=\"cpu\"}, \"instance\", \"$1\", \"node_name\", \"(.*)\")\n    )\n)",
       "legendFormat": "{{instance_type}}"
      }
     ]
    },
    {
     "title": "AWS | Average CPU Usage By Type",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 168 },
     "targets": [
      {
       "expr": "avg by (instance_type, container) (\n    rate(container_cpu_usage_seconds_total{\n        cluster=\"$cluster\",\n        namespace=\"$namespace\",\n        container=~\"segment-writer|distributor|cortex-gw\",\n    }[$__rate_interval]) + on (instance) group_left(instance_type) (0 * label_replace(\n        karpenter_nodes_allocatable{cluster=\"$cluster\", resource_type=\"cpu\"}, \"instance\", \"$1\", \"node_name\", \"(.*)\")\n    )\n)",
       "legendFormat": "{{container}}/{{instance_type}}"
      }
     ]
    }
   ]
  }
 ]
}