// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: metastore/raftnode/raftnodepb/raft_node.proto

package raftnodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RaftNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftNode) Reset() {
	*x = RaftNode{}
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftNode) ProtoMessage() {}

func (x *RaftNode) ProtoReflect() protoreflect.Message {
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftNode.ProtoReflect.Descriptor instead.
func (*RaftNode) Descriptor() ([]byte, []int) {
	return file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescGZIP(), []int{0}
}

func (x *RaftNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RaftNode) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ReadIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadIndexRequest) Reset() {
	*x = ReadIndexRequest{}
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadIndexRequest) ProtoMessage() {}

func (x *ReadIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadIndexRequest.ProtoReflect.Descriptor instead.
func (*ReadIndexRequest) Descriptor() ([]byte, []int) {
	return file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescGZIP(), []int{1}
}

type ReadIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitIndex   uint64                 `protobuf:"varint,1,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadIndexResponse) Reset() {
	*x = ReadIndexResponse{}
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadIndexResponse) ProtoMessage() {}

func (x *ReadIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadIndexResponse.ProtoReflect.Descriptor instead.
func (*ReadIndexResponse) Descriptor() ([]byte, []int) {
	return file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescGZIP(), []int{2}
}

func (x *ReadIndexResponse) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *ReadIndexResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type NodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfoRequest) Reset() {
	*x = NodeInfoRequest{}
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfoRequest) ProtoMessage() {}

func (x *NodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfoRequest.ProtoReflect.Descriptor instead.
func (*NodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescGZIP(), []int{3}
}

type NodeInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfoResponse) Reset() {
	*x = NodeInfoResponse{}
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfoResponse) ProtoMessage() {}

func (x *NodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfoResponse.ProtoReflect.Descriptor instead.
func (*NodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescGZIP(), []int{4}
}

func (x *NodeInfoResponse) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type NodeInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ServerId           string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	AdvertisedAddress  string                 `protobuf:"bytes,2,opt,name=advertised_address,json=advertisedAddress,proto3" json:"advertised_address,omitempty"`
	State              string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	LeaderId           string                 `protobuf:"bytes,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	CommitIndex        uint64                 `protobuf:"varint,5,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	AppliedIndex       uint64                 `protobuf:"varint,6,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	LastIndex          uint64                 `protobuf:"varint,7,opt,name=last_index,json=lastIndex,proto3" json:"last_index,omitempty"`
	Stats              *NodeInfo_Stats        `protobuf:"bytes,8,opt,name=stats,proto3" json:"stats,omitempty"`
	Peers              []*NodeInfo_Peer       `protobuf:"bytes,9,rep,name=peers,proto3" json:"peers,omitempty"`
	ConfigurationIndex uint64                 `protobuf:"varint,10,opt,name=configuration_index,json=configurationIndex,proto3" json:"configuration_index,omitempty"`
	CurrentTerm        uint64                 `protobuf:"varint,11,opt,name=current_term,json=currentTerm,proto3" json:"current_term,omitempty"`
	BuildVersion       string                 `protobuf:"bytes,12,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	BuildRevision      string                 `protobuf:"bytes,13,opt,name=build_revision,json=buildRevision,proto3" json:"build_revision,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescGZIP(), []int{5}
}

func (x *NodeInfo) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *NodeInfo) GetAdvertisedAddress() string {
	if x != nil {
		return x.AdvertisedAddress
	}
	return ""
}

func (x *NodeInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *NodeInfo) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *NodeInfo) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *NodeInfo) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *NodeInfo) GetLastIndex() uint64 {
	if x != nil {
		return x.LastIndex
	}
	return 0
}

func (x *NodeInfo) GetStats() *NodeInfo_Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *NodeInfo) GetPeers() []*NodeInfo_Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *NodeInfo) GetConfigurationIndex() uint64 {
	if x != nil {
		return x.ConfigurationIndex
	}
	return 0
}

func (x *NodeInfo) GetCurrentTerm() uint64 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *NodeInfo) GetBuildVersion() string {
	if x != nil {
		return x.BuildVersion
	}
	return ""
}

func (x *NodeInfo) GetBuildRevision() string {
	if x != nil {
		return x.BuildRevision
	}
	return ""
}

type RemoveNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CurrentTerm   uint64                 `protobuf:"varint,2,opt,name=current_term,json=currentTerm,proto3" json:"current_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeRequest) Reset() {
	*x = RemoveNodeRequest{}
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeRequest) ProtoMessage() {}

func (x *RemoveNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeRequest.ProtoReflect.Descriptor instead.
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveNodeRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RemoveNodeRequest) GetCurrentTerm() uint64 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

type RemoveNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeResponse) Reset() {
	*x = RemoveNodeResponse{}
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeResponse) ProtoMessage() {}

func (x *RemoveNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeResponse.ProtoReflect.Descriptor instead.
func (*RemoveNodeResponse) Descriptor() ([]byte, []int) {
	return file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescGZIP(), []int{7}
}

type AddNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CurrentTerm   uint64                 `protobuf:"varint,2,opt,name=current_term,json=currentTerm,proto3" json:"current_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeRequest) Reset() {
	*x = AddNodeRequest{}
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeRequest) ProtoMessage() {}

func (x *AddNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeRequest.ProtoReflect.Descriptor instead.
func (*AddNodeRequest) Descriptor() ([]byte, []int) {
	return file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescGZIP(), []int{8}
}

func (x *AddNodeRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AddNodeRequest) GetCurrentTerm() uint64 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

type AddNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeResponse) Reset() {
	*x = AddNodeResponse{}
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeResponse) ProtoMessage() {}

func (x *AddNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeResponse.ProtoReflect.Descriptor instead.
func (*AddNodeResponse) Descriptor() ([]byte, []int) {
	return file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescGZIP(), []int{9}
}

type DemoteLeaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CurrentTerm   uint64                 `protobuf:"varint,2,opt,name=current_term,json=currentTerm,proto3" json:"current_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoteLeaderRequest) Reset() {
	*x = DemoteLeaderRequest{}
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoteLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoteLeaderRequest) ProtoMessage() {}

func (x *DemoteLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoteLeaderRequest.ProtoReflect.Descriptor instead.
func (*DemoteLeaderRequest) Descriptor() ([]byte, []int) {
	return file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescGZIP(), []int{10}
}

func (x *DemoteLeaderRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *DemoteLeaderRequest) GetCurrentTerm() uint64 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

type DemoteLeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoteLeaderResponse) Reset() {
	*x = DemoteLeaderResponse{}
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoteLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoteLeaderResponse) ProtoMessage() {}

func (x *DemoteLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoteLeaderResponse.ProtoReflect.Descriptor instead.
func (*DemoteLeaderResponse) Descriptor() ([]byte, []int) {
	return file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescGZIP(), []int{11}
}

type PromoteToLeaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CurrentTerm   uint64                 `protobuf:"varint,2,opt,name=current_term,json=currentTerm,proto3" json:"current_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteToLeaderRequest) Reset() {
	*x = PromoteToLeaderRequest{}
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteToLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteToLeaderRequest) ProtoMessage() {}

func (x *PromoteToLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteToLeaderRequest.ProtoReflect.Descriptor instead.
func (*PromoteToLeaderRequest) Descriptor() ([]byte, []int) {
	return file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescGZIP(), []int{12}
}

func (x *PromoteToLeaderRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *PromoteToLeaderRequest) GetCurrentTerm() uint64 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

type PromoteToLeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteToLeaderResponse) Reset() {
	*x = PromoteToLeaderResponse{}
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteToLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteToLeaderResponse) ProtoMessage() {}

func (x *PromoteToLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteToLeaderResponse.ProtoReflect.Descriptor instead.
func (*PromoteToLeaderResponse) Descriptor() ([]byte, []int) {
	return file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescGZIP(), []int{13}
}

type NodeInfo_Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          []string               `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	Value         []string               `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo_Stats) Reset() {
	*x = NodeInfo_Stats{}
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo_Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo_Stats) ProtoMessage() {}

func (x *NodeInfo_Stats) ProtoReflect() protoreflect.Message {
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo_Stats.ProtoReflect.Descriptor instead.
func (*NodeInfo_Stats) Descriptor() ([]byte, []int) {
	return file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescGZIP(), []int{5, 0}
}

func (x *NodeInfo_Stats) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *NodeInfo_Stats) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type NodeInfo_Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerAddress string                 `protobuf:"bytes,2,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	Suffrage      string                 `protobuf:"bytes,3,opt,name=suffrage,proto3" json:"suffrage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo_Peer) Reset() {
	*x = NodeInfo_Peer{}
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo_Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo_Peer) ProtoMessage() {}

func (x *NodeInfo_Peer) ProtoReflect() protoreflect.Message {
	mi := &file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo_Peer.ProtoReflect.Descriptor instead.
func (*NodeInfo_Peer) Descriptor() ([]byte, []int) {
	return file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescGZIP(), []int{5, 1}
}

func (x *NodeInfo_Peer) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *NodeInfo_Peer) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *NodeInfo_Peer) GetSuffrage() string {
	if x != nil {
		return x.Suffrage
	}
	return ""
}

var File_metastore_raftnode_raftnodepb_raft_node_proto protoreflect.FileDescriptor

const file_metastore_raftnode_raftnodepb_raft_node_proto_rawDesc = "" +
	"\n" +
	"-metastore/raftnode/raftnodepb/raft_node.proto\x12\traft_node\"4\n" +
	"\bRaftNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\x12\n" +
	"\x10ReadIndexRequest\"J\n" +
	"\x11ReadIndexResponse\x12!\n" +
	"\fcommit_index\x18\x01 \x01(\x04R\vcommitIndex\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\"\x11\n" +
	"\x0fNodeInfoRequest\";\n" +
	"\x10NodeInfoResponse\x12'\n" +
	"\x04node\x18\x01 \x01(\v2\x13.raft_node.NodeInfoR\x04node\"\x8c\x05\n" +
	"\bNodeInfo\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12-\n" +
	"\x12advertised_address\x18\x02 \x01(\tR\x11advertisedAddress\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\tR\bleaderId\x12!\n" +
	"\fcommit_index\x18\x05 \x01(\x04R\vcommitIndex\x12#\n" +
	"\rapplied_index\x18\x06 \x01(\x04R\fappliedIndex\x12\x1d\n" +
	"\n" +
	"last_index\x18\a \x01(\x04R\tlastIndex\x12/\n" +
	"\x05stats\x18\b \x01(\v2\x19.raft_node.NodeInfo.StatsR\x05stats\x12.\n" +
	"\x05peers\x18\t \x03(\v2\x18.raft_node.NodeInfo.PeerR\x05peers\x12/\n" +
	"\x13configuration_index\x18\n" +
	" \x01(\x04R\x12configurationIndex\x12!\n" +
	"\fcurrent_term\x18\v \x01(\x04R\vcurrentTerm\x12#\n" +
	"\rbuild_version\x18\f \x01(\tR\fbuildVersion\x12%\n" +
	"\x0ebuild_revision\x18\r \x01(\tR\rbuildRevision\x1a1\n" +
	"\x05Stats\x12\x12\n" +
	"\x04name\x18\x01 \x03(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x03(\tR\x05value\x1af\n" +
	"\x04Peer\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12%\n" +
	"\x0eserver_address\x18\x02 \x01(\tR\rserverAddress\x12\x1a\n" +
	"\bsuffrage\x18\x03 \x01(\tR\bsuffrage\"S\n" +
	"\x11RemoveNodeRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12!\n" +
	"\fcurrent_term\x18\x02 \x01(\x04R\vcurrentTerm\"\x14\n" +
	"\x12RemoveNodeResponse\"P\n" +
	"\x0eAddNodeRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12!\n" +
	"\fcurrent_term\x18\x02 \x01(\x04R\vcurrentTerm\"\x11\n" +
	"\x0fAddNodeResponse\"U\n" +
	"\x13DemoteLeaderRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12!\n" +
	"\fcurrent_term\x18\x02 \x01(\x04R\vcurrentTerm\"\x16\n" +
	"\x14DemoteLeaderResponse\"X\n" +
	"\x16PromoteToLeaderRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12!\n" +
	"\fcurrent_term\x18\x02 \x01(\x04R\vcurrentTerm\"\x19\n" +
	"\x17PromoteToLeaderResponse2\xe2\x03\n" +
	"\x0fRaftNodeService\x12H\n" +
	"\tReadIndex\x12\x1b.raft_node.ReadIndexRequest\x1a\x1c.raft_node.ReadIndexResponse\"\x00\x12E\n" +
	"\bNodeInfo\x12\x1a.raft_node.NodeInfoRequest\x1a\x1b.raft_node.NodeInfoResponse\"\x00\x12K\n" +
	"\n" +
	"RemoveNode\x12\x1c.raft_node.RemoveNodeRequest\x1a\x1d.raft_node.RemoveNodeResponse\"\x00\x12B\n" +
	"\aAddNode\x12\x19.raft_node.AddNodeRequest\x1a\x1a.raft_node.AddNodeResponse\"\x00\x12Q\n" +
	"\fDemoteLeader\x12\x1e.raft_node.DemoteLeaderRequest\x1a\x1f.raft_node.DemoteLeaderResponse\"\x00\x12Z\n" +
	"\x0fPromoteToLeader\x12!.raft_node.PromoteToLeaderRequest\x1a\".raft_node.PromoteToLeaderResponse\"\x00B\x9e\x01\n" +
	"\rcom.raft_nodeB\rRaftNodeProtoP\x01Z>github.com/grafana/pyroscope/pkg/metastore/raftnode/raftnodepb\xa2\x02\x03RXX\xaa\x02\bRaftNode\xca\x02\bRaftNode\xe2\x02\x14RaftNode\\GPBMetadata\xea\x02\bRaftNodeb\x06proto3"

var (
	file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescOnce sync.Once
	file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescData []byte
)

func file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescGZIP() []byte {
	file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescOnce.Do(func() {
		file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metastore_raftnode_raftnodepb_raft_node_proto_rawDesc), len(file_metastore_raftnode_raftnodepb_raft_node_proto_rawDesc)))
	})
	return file_metastore_raftnode_raftnodepb_raft_node_proto_rawDescData
}

var file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_metastore_raftnode_raftnodepb_raft_node_proto_goTypes = []any{
	(*RaftNode)(nil),                // 0: raft_node.RaftNode
	(*ReadIndexRequest)(nil),        // 1: raft_node.ReadIndexRequest
	(*ReadIndexResponse)(nil),       // 2: raft_node.ReadIndexResponse
	(*NodeInfoRequest)(nil),         // 3: raft_node.NodeInfoRequest
	(*NodeInfoResponse)(nil),        // 4: raft_node.NodeInfoResponse
	(*NodeInfo)(nil),                // 5: raft_node.NodeInfo
	(*RemoveNodeRequest)(nil),       // 6: raft_node.RemoveNodeRequest
	(*RemoveNodeResponse)(nil),      // 7: raft_node.RemoveNodeResponse
	(*AddNodeRequest)(nil),          // 8: raft_node.AddNodeRequest
	(*AddNodeResponse)(nil),         // 9: raft_node.AddNodeResponse
	(*DemoteLeaderRequest)(nil),     // 10: raft_node.DemoteLeaderRequest
	(*DemoteLeaderResponse)(nil),    // 11: raft_node.DemoteLeaderResponse
	(*PromoteToLeaderRequest)(nil),  // 12: raft_node.PromoteToLeaderRequest
	(*PromoteToLeaderResponse)(nil), // 13: raft_node.PromoteToLeaderResponse
	(*NodeInfo_Stats)(nil),          // 14: raft_node.NodeInfo.Stats
	(*NodeInfo_Peer)(nil),           // 15: raft_node.NodeInfo.Peer
}
var file_metastore_raftnode_raftnodepb_raft_node_proto_depIdxs = []int32{
	5,  // 0: raft_node.NodeInfoResponse.node:type_name -> raft_node.NodeInfo
	14, // 1: raft_node.NodeInfo.stats:type_name -> raft_node.NodeInfo.Stats
	15, // 2: raft_node.NodeInfo.peers:type_name -> raft_node.NodeInfo.Peer
	1,  // 3: raft_node.RaftNodeService.ReadIndex:input_type -> raft_node.ReadIndexRequest
	3,  // 4: raft_node.RaftNodeService.NodeInfo:input_type -> raft_node.NodeInfoRequest
	6,  // 5: raft_node.RaftNodeService.RemoveNode:input_type -> raft_node.RemoveNodeRequest
	8,  // 6: raft_node.RaftNodeService.AddNode:input_type -> raft_node.AddNodeRequest
	10, // 7: raft_node.RaftNodeService.DemoteLeader:input_type -> raft_node.DemoteLeaderRequest
	12, // 8: raft_node.RaftNodeService.PromoteToLeader:input_type -> raft_node.PromoteToLeaderRequest
	2,  // 9: raft_node.RaftNodeService.ReadIndex:output_type -> raft_node.ReadIndexResponse
	4,  // 10: raft_node.RaftNodeService.NodeInfo:output_type -> raft_node.NodeInfoResponse
	7,  // 11: raft_node.RaftNodeService.RemoveNode:output_type -> raft_node.RemoveNodeResponse
	9,  // 12: raft_node.RaftNodeService.AddNode:output_type -> raft_node.AddNodeResponse
	11, // 13: raft_node.RaftNodeService.DemoteLeader:output_type -> raft_node.DemoteLeaderResponse
	13, // 14: raft_node.RaftNodeService.PromoteToLeader:output_type -> raft_node.PromoteToLeaderResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_metastore_raftnode_raftnodepb_raft_node_proto_init() }
func file_metastore_raftnode_raftnodepb_raft_node_proto_init() {
	if File_metastore_raftnode_raftnodepb_raft_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metastore_raftnode_raftnodepb_raft_node_proto_rawDesc), len(file_metastore_raftnode_raftnodepb_raft_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metastore_raftnode_raftnodepb_raft_node_proto_goTypes,
		DependencyIndexes: file_metastore_raftnode_raftnodepb_raft_node_proto_depIdxs,
		MessageInfos:      file_metastore_raftnode_raftnodepb_raft_node_proto_msgTypes,
	}.Build()
	File_metastore_raftnode_raftnodepb_raft_node_proto = out.File
	file_metastore_raftnode_raftnodepb_raft_node_proto_goTypes = nil
	file_metastore_raftnode_raftnodepb_raft_node_proto_depIdxs = nil
}
