openapi: 3.1.0
info:
  title: debuginfo.v1alpha1
  version: v1.0.0
tags:
  - name: scope/public
    description: This operation is considered part of the public API scope
  - name: scope/internal
    description: This operation is considered part of the interal API scope. There are no stability guaraentees when using those APIs.
  - name: debuginfo.v1alpha1.DebuginfoService
paths:
  /debuginfo.v1alpha1.DebuginfoService/ListDebuginfo:
    post:
      tags:
        - debuginfo.v1alpha1.DebuginfoService
      summary: ListDebuginfo
      operationId: debuginfo.v1alpha1.DebuginfoService.ListDebuginfo
      parameters:
        - name: Connect-Protocol-Version
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/connect-protocol-version'
        - name: Connect-Timeout-Ms
          in: header
          schema:
            $ref: '#/components/schemas/connect-timeout-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/debuginfo.v1alpha1.ListDebuginfoRequest'
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.error'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/debuginfo.v1alpha1.ListDebuginfoResponse'
  /debuginfo.v1alpha1.DebuginfoService/ShouldInitiateUpload:
    post:
      tags:
        - debuginfo.v1alpha1.DebuginfoService
      summary: ShouldInitiateUpload
      operationId: debuginfo.v1alpha1.DebuginfoService.ShouldInitiateUpload
      parameters:
        - name: Connect-Protocol-Version
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/connect-protocol-version'
        - name: Connect-Timeout-Ms
          in: header
          schema:
            $ref: '#/components/schemas/connect-timeout-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/debuginfo.v1alpha1.ShouldInitiateUploadRequest'
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.error'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/debuginfo.v1alpha1.ShouldInitiateUploadResponse'
  /debuginfo.v1alpha1.DebuginfoService/UploadFinished:
    post:
      tags:
        - debuginfo.v1alpha1.DebuginfoService
      summary: UploadFinished
      operationId: debuginfo.v1alpha1.DebuginfoService.UploadFinished
      parameters:
        - name: Connect-Protocol-Version
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/connect-protocol-version'
        - name: Connect-Timeout-Ms
          in: header
          schema:
            $ref: '#/components/schemas/connect-timeout-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/debuginfo.v1alpha1.UploadFinishedRequest'
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.error'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/debuginfo.v1alpha1.UploadFinishedResponse'
components:
  schemas:
    connect-protocol-version:
      type: number
      title: Connect-Protocol-Version
      enum:
        - 1
      description: Define the version of the Connect protocol
      const: 1
    connect-timeout-header:
      type: number
      title: Connect-Timeout-Ms
      description: Define the timeout, in ms
    connect.error:
      type: object
      properties:
        code:
          type: string
          examples:
            - not_found
          enum:
            - canceled
            - unknown
            - invalid_argument
            - deadline_exceeded
            - not_found
            - already_exists
            - permission_denied
            - resource_exhausted
            - failed_precondition
            - aborted
            - out_of_range
            - unimplemented
            - internal
            - unavailable
            - data_loss
            - unauthenticated
          description: The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
        message:
          type: string
          description: A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
        details:
          type: array
          items:
            $ref: '#/components/schemas/connect.error_details.Any'
          description: A list of messages that carry the error details. There is no limit on the number of messages.
      title: Connect Error
      additionalProperties: true
      description: 'Error type returned by Connect: https://connectrpc.com/docs/go/errors/#http-representation'
    connect.error_details.Any:
      type: object
      properties:
        type:
          type: string
          description: 'A URL that acts as a globally unique identifier for the type of the serialized message. For example: `type.googleapis.com/google.rpc.ErrorInfo`. This is used to determine the schema of the data in the `value` field and is the discriminator for the `debug` field.'
        value:
          type: string
          format: binary
          description: The Protobuf message, serialized as bytes and base64-encoded. The specific message type is identified by the `type` field.
        debug:
          oneOf:
            - type: object
              title: Any
              additionalProperties: true
              description: Detailed error information.
          discriminator:
            propertyName: type
          title: Debug
          description: Deserialized error detail payload. The 'type' field indicates the schema. This field is for easier debugging and should not be relied upon for application logic.
      additionalProperties: true
      description: Contains an arbitrary serialized message along with a @type that describes the type of the serialized message, with an additional debug field for ConnectRPC error details.
    debuginfo.v1alpha1.FileMetadata:
      type: object
      properties:
        gnuBuildId:
          type: string
          title: gnu_build_id
          description: GNU build ID of the executable.
        goBuildId:
          type: string
          title: go_build_id
          description: Go build ID of the executable.
        otelFileId:
          type: string
          title: otel_file_id
          description: Optional libpf.FileID from the otel profiler.
        name:
          type: string
          title: name
          description: Original file name of the executable.
        type:
          title: type
          description: Type of the debug info.
          $ref: '#/components/schemas/debuginfo.v1alpha1.FileMetadata.Type'
      title: FileMetadata
      additionalProperties: false
    debuginfo.v1alpha1.FileMetadata.Type:
      type: string
      title: Type
      enum:
        - TYPE_UNSPECIFIED
        - TYPE_EXECUTABLE_FULL
        - TYPE_EXECUTABLE_NO_TEXT
    debuginfo.v1alpha1.ListDebuginfoRequest:
      type: object
      title: ListDebuginfoRequest
      additionalProperties: false
    debuginfo.v1alpha1.ListDebuginfoResponse:
      type: object
      properties:
        object:
          type: array
          items:
            $ref: '#/components/schemas/debuginfo.v1alpha1.ObjectMetadata'
          title: object
      title: ListDebuginfoResponse
      additionalProperties: false
    debuginfo.v1alpha1.ObjectMetadata:
      type: object
      properties:
        file:
          title: file
          $ref: '#/components/schemas/debuginfo.v1alpha1.FileMetadata'
        state:
          title: state
          $ref: '#/components/schemas/debuginfo.v1alpha1.ObjectMetadata.State'
        startedAt:
          title: started_at
          $ref: '#/components/schemas/google.protobuf.Timestamp'
        finishedAt:
          title: finished_at
          $ref: '#/components/schemas/google.protobuf.Timestamp'
        sizeBytes:
          type:
            - integer
            - string
          title: size_bytes
          format: int64
          description: Size of the uploaded ELF file in bytes.
      title: ObjectMetadata
      additionalProperties: false
      description: |-
        This is stored in buckets at "debug-info/$tenant/$gnu_build_id/metadata"
         Along with the actual uploaded file at "debug-info/$tenant/$gnu_build_id/exe"
    debuginfo.v1alpha1.ObjectMetadata.State:
      type: string
      title: State
      enum:
        - STATE_UPLOADING
        - STATE_UPLOADED
    debuginfo.v1alpha1.ShouldInitiateUploadRequest:
      type: object
      properties:
        file:
          title: file
          $ref: '#/components/schemas/debuginfo.v1alpha1.FileMetadata'
      title: ShouldInitiateUploadRequest
      additionalProperties: false
    debuginfo.v1alpha1.ShouldInitiateUploadResponse:
      type: object
      properties:
        shouldInitiateUpload:
          type: boolean
          title: should_initiate_upload
        reason:
          type: string
          title: reason
      title: ShouldInitiateUploadResponse
      additionalProperties: false
    debuginfo.v1alpha1.UploadFinishedRequest:
      type: object
      properties:
        gnuBuildId:
          type: string
          title: gnu_build_id
      title: UploadFinishedRequest
      additionalProperties: false
    debuginfo.v1alpha1.UploadFinishedResponse:
      type: object
      title: UploadFinishedResponse
      additionalProperties: false
    google.protobuf.Timestamp:
      type: string
      examples:
        - "2023-01-15T01:30:15.01Z"
        - "2024-12-25T12:00:00Z"
      format: date-time
      description: |-
        A Timestamp represents a point in time independent of any time zone or local
         calendar, encoded as a count of seconds and fractions of seconds at
         nanosecond resolution. The count is relative to an epoch at UTC midnight on
         January 1, 1970, in the proleptic Gregorian calendar which extends the
         Gregorian calendar backwards to year one.

         All minutes are 60 seconds long. Leap seconds are "smeared" so that no leap
         second table is needed for interpretation, using a [24-hour linear
         smear](https://developers.google.com/time/smear).

         The range is from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59.999999999Z. By
         restricting to that range, we ensure that we can convert to and from [RFC
         3339](https://www.ietf.org/rfc/rfc3339.txt) date strings.

         # Examples

         Example 1: Compute Timestamp from POSIX `time()`.

             Timestamp timestamp;
             timestamp.set_seconds(time(NULL));
             timestamp.set_nanos(0);

         Example 2: Compute Timestamp from POSIX `gettimeofday()`.

             struct timeval tv;
             gettimeofday(&tv, NULL);

             Timestamp timestamp;
             timestamp.set_seconds(tv.tv_sec);
             timestamp.set_nanos(tv.tv_usec * 1000);

         Example 3: Compute Timestamp from Win32 `GetSystemTimeAsFileTime()`.

             FILETIME ft;
             GetSystemTimeAsFileTime(&ft);
             UINT64 ticks = (((UINT64)ft.dwHighDateTime) << 32) | ft.dwLowDateTime;

             // A Windows tick is 100 nanoseconds. Windows epoch 1601-01-01T00:00:00Z
             // is 11644473600 seconds before Unix epoch 1970-01-01T00:00:00Z.
             Timestamp timestamp;
             timestamp.set_seconds((INT64) ((ticks / 10000000) - 11644473600LL));
             timestamp.set_nanos((INT32) ((ticks % 10000000) * 100));

         Example 4: Compute Timestamp from Java `System.currentTimeMillis()`.

             long millis = System.currentTimeMillis();

             Timestamp timestamp = Timestamp.newBuilder().setSeconds(millis / 1000)
                 .setNanos((int) ((millis % 1000) * 1000000)).build();

         Example 5: Compute Timestamp from Java `Instant.now()`.

             Instant now = Instant.now();

             Timestamp timestamp =
                 Timestamp.newBuilder().setSeconds(now.getEpochSecond())
                     .setNanos(now.getNano()).build();

         Example 6: Compute Timestamp from current time in Python.

             timestamp = Timestamp()
             timestamp.GetCurrentTime()

         # JSON Mapping

         In JSON format, the Timestamp type is encoded as a string in the
         [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format. That is, the
         format is "{year}-{month}-{day}T{hour}:{min}:{sec}[.{frac_sec}]Z"
         where {year} is always expressed using four digits while {month}, {day},
         {hour}, {min}, and {sec} are zero-padded to two digits each. The fractional
         seconds, which can go up to 9 digits (i.e. up to 1 nanosecond resolution),
         are optional. The "Z" suffix indicates the timezone ("UTC"); the timezone
         is required. A proto3 JSON serializer should always use UTC (as indicated by
         "Z") when printing the Timestamp type and a proto3 JSON parser should be
         able to accept both UTC and other timezones (as indicated by an offset).

         For example, "2017-01-15T01:30:15.01Z" encodes 15.01 seconds past
         01:30 UTC on January 15, 2017.

         In JavaScript, one can convert a Date object to this format using the
         standard
         [toISOString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString)
         method. In Python, a standard `datetime.datetime` object can be converted
         to this format using
         [`strftime`](https://docs.python.org/2/library/time.html#time.strftime) with
         the time format spec '%Y-%m-%dT%H:%M:%S.%fZ'. Likewise, in Java, one can use
         the Joda Time's [`ISODateTimeFormat.dateTime()`](
         http://joda-time.sourceforge.net/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateTime()
         ) to obtain a formatter capable of generating timestamps in this format.
security: []
