// SPDX-License-Identifier: AGPL-3.0-only
// Provenance-includes-location: https://github.com/cortexproject/cortex/blob/master/pkg/querier/stats/stats.proto
// Provenance-includes-license: Apache-2.0
// Provenance-includes-copyright: The Cortex Authors.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: querier/stats/stats.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sum of all wall time spent in the querier to execute the query.
	WallTime int64 `protobuf:"varint,1,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	// The number of series fetched for the query
	FetchedSeriesCount uint64 `protobuf:"varint,2,opt,name=fetched_series_count,json=fetchedSeriesCount,proto3" json:"fetched_series_count,omitempty"`
	// The number of bytes of the chunks fetched for the query
	FetchedChunkBytes uint64 `protobuf:"varint,3,opt,name=fetched_chunk_bytes,json=fetchedChunkBytes,proto3" json:"fetched_chunk_bytes,omitempty"`
	// The number of chunks fetched for the query
	FetchedChunksCount uint64 `protobuf:"varint,4,opt,name=fetched_chunks_count,json=fetchedChunksCount,proto3" json:"fetched_chunks_count,omitempty"`
	// The number of sharded queries executed. 0 if sharding is disabled or the query can't be sharded.
	ShardedQueries uint32 `protobuf:"varint,5,opt,name=sharded_queries,json=shardedQueries,proto3" json:"sharded_queries,omitempty"`
	// The number of split partial queries executed. 0 if splitting is disabled or the query can't be split.
	SplitQueries uint32 `protobuf:"varint,6,opt,name=split_queries,json=splitQueries,proto3" json:"split_queries,omitempty"`
	// The number of index bytes fetched on the store-gateway for the query
	FetchedIndexBytes uint64 `protobuf:"varint,7,opt,name=fetched_index_bytes,json=fetchedIndexBytes,proto3" json:"fetched_index_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_querier_stats_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_querier_stats_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_querier_stats_stats_proto_rawDescGZIP(), []int{0}
}

func (x *Stats) GetWallTime() int64 {
	if x != nil {
		return x.WallTime
	}
	return 0
}

func (x *Stats) GetFetchedSeriesCount() uint64 {
	if x != nil {
		return x.FetchedSeriesCount
	}
	return 0
}

func (x *Stats) GetFetchedChunkBytes() uint64 {
	if x != nil {
		return x.FetchedChunkBytes
	}
	return 0
}

func (x *Stats) GetFetchedChunksCount() uint64 {
	if x != nil {
		return x.FetchedChunksCount
	}
	return 0
}

func (x *Stats) GetShardedQueries() uint32 {
	if x != nil {
		return x.ShardedQueries
	}
	return 0
}

func (x *Stats) GetSplitQueries() uint32 {
	if x != nil {
		return x.SplitQueries
	}
	return 0
}

func (x *Stats) GetFetchedIndexBytes() uint64 {
	if x != nil {
		return x.FetchedIndexBytes
	}
	return 0
}

var File_querier_stats_stats_proto protoreflect.FileDescriptor

const file_querier_stats_stats_proto_rawDesc = "" +
	"\n" +
	"\x19querier/stats/stats.proto\x12\x05stats\"\xb6\x02\n" +
	"\x05Stats\x12\x1b\n" +
	"\twall_time\x18\x01 \x01(\x03R\bwallTime\x120\n" +
	"\x14fetched_series_count\x18\x02 \x01(\x04R\x12fetchedSeriesCount\x12.\n" +
	"\x13fetched_chunk_bytes\x18\x03 \x01(\x04R\x11fetchedChunkBytes\x120\n" +
	"\x14fetched_chunks_count\x18\x04 \x01(\x04R\x12fetchedChunksCount\x12'\n" +
	"\x0fsharded_queries\x18\x05 \x01(\rR\x0eshardedQueries\x12#\n" +
	"\rsplit_queries\x18\x06 \x01(\rR\fsplitQueries\x12.\n" +
	"\x13fetched_index_bytes\x18\a \x01(\x04R\x11fetchedIndexBytesB{\n" +
	"\tcom.statsB\n" +
	"StatsProtoP\x01Z.github.com/grafana/pyroscope/pkg/querier/stats\xa2\x02\x03SXX\xaa\x02\x05Stats\xca\x02\x05Stats\xe2\x02\x11Stats\\GPBMetadata\xea\x02\x05Statsb\x06proto3"

var (
	file_querier_stats_stats_proto_rawDescOnce sync.Once
	file_querier_stats_stats_proto_rawDescData []byte
)

func file_querier_stats_stats_proto_rawDescGZIP() []byte {
	file_querier_stats_stats_proto_rawDescOnce.Do(func() {
		file_querier_stats_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_querier_stats_stats_proto_rawDesc), len(file_querier_stats_stats_proto_rawDesc)))
	})
	return file_querier_stats_stats_proto_rawDescData
}

var file_querier_stats_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_querier_stats_stats_proto_goTypes = []any{
	(*Stats)(nil), // 0: stats.Stats
}
var file_querier_stats_stats_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_querier_stats_stats_proto_init() }
func file_querier_stats_stats_proto_init() {
	if File_querier_stats_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_querier_stats_stats_proto_rawDesc), len(file_querier_stats_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_querier_stats_stats_proto_goTypes,
		DependencyIndexes: file_querier_stats_stats_proto_depIdxs,
		MessageInfos:      file_querier_stats_stats_proto_msgTypes,
	}.Build()
	File_querier_stats_stats_proto = out.File
	file_querier_stats_stats_proto_goTypes = nil
	file_querier_stats_stats_proto_depIdxs = nil
}
