// Code generated by mockery. DO NOT EDIT.

package mockotlp

import (
	context "context"

	connect "connectrpc.com/connect"

	mock "github.com/stretchr/testify/mock"

	model "github.com/grafana/pyroscope/pkg/distributor/model"

	pushv1 "github.com/grafana/pyroscope/api/gen/proto/go/push/v1"
)

// MockPushService is an autogenerated mock type for the PushService type
type MockPushService struct {
	mock.Mock
}

type MockPushService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPushService) EXPECT() *MockPushService_Expecter {
	return &MockPushService_Expecter{mock: &_m.Mock}
}

// PushParsed provides a mock function with given fields: ctx, req
func (_m *MockPushService) PushParsed(ctx context.Context, req *model.PushRequest) (*connect.Response[pushv1.PushResponse], error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PushParsed")
	}

	var r0 *connect.Response[pushv1.PushResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.PushRequest) (*connect.Response[pushv1.PushResponse], error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.PushRequest) *connect.Response[pushv1.PushResponse]); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connect.Response[pushv1.PushResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.PushRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPushService_PushParsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushParsed'
type MockPushService_PushParsed_Call struct {
	*mock.Call
}

// PushParsed is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.PushRequest
func (_e *MockPushService_Expecter) PushParsed(ctx interface{}, req interface{}) *MockPushService_PushParsed_Call {
	return &MockPushService_PushParsed_Call{Call: _e.mock.On("PushParsed", ctx, req)}
}

func (_c *MockPushService_PushParsed_Call) Run(run func(ctx context.Context, req *model.PushRequest)) *MockPushService_PushParsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.PushRequest))
	})
	return _c
}

func (_c *MockPushService_PushParsed_Call) Return(_a0 *connect.Response[pushv1.PushResponse], _a1 error) *MockPushService_PushParsed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPushService_PushParsed_Call) RunAndReturn(run func(context.Context, *model.PushRequest) (*connect.Response[pushv1.PushResponse], error)) *MockPushService_PushParsed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPushService creates a new instance of MockPushService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPushService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPushService {
	mock := &MockPushService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
