FROM golang:1.16

RUN git clone https://github.com/nsqio/nsq.git $GOPATH/src/nsq
WORKDIR $GOPATH/src/nsq/apps/nsqd

COPY main/nsqd main.go
RUN GO111MODULE=on go mod tidy
RUN GO111MODULE=on go build
RUN chmod +x nsqd

ENTRYPOINT ["./nsqd"]

