FROM golang:1.16

RUN git clone https://github.com/rqlite/rqlite.git $GOPATH/src/rqlite
WORKDIR $GOPATH/src/rqlite/cmd/rqlited

COPY main/rqlite main.go
RUN GO111MODULE=on go mod tidy
RUN GO111MODULE=on go build
RUN chmod +x rqlited

ENTRYPOINT ["./rqlited", "~/node.1"]