FROM golang:1.16

RUN git clone https://github.com/centrifugal/centrifugo.git $GOPATH/src/centrifugo
WORKDIR $GOPATH/src/centrifugo

COPY main/centrifugo main.go
RUN GO111MODULE=on go mod tidy
RUN GO111MODULE=on go build
RUN chmod +x centrifugo
RUN ./centrifugo genconfig

ENTRYPOINT ["./centrifugo"]