{
 "title": "main",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"mem_.+\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"disk_.+\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "graph",
   "description": "Number of objects in cache",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"cache_.+\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Run Progress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "run_progress", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Stats",
   "type": "text",
   "description": "a lot symbols are replaces with dashes or removed",
   "gridPos": { "h": 30, "w": 6, "x": 18, "y": 6 },
   "options": {
    "content": "<iframe style=\"border:none; width:100%; height: 100%;\" src=\"http://localhost:8081/summary\">"
   },
   "targets": [
    {
     "expr": "{__name__=~\"stats_.+\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"go_memstats_.+bytes\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Upload Errors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "upload_errors", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Successful Uploads",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "successful_uploads", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"go_goroutines\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "RAM Evictions",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ram_evictions_alloc_bytes{}", "legendFormat": "{{__name__}}" },
    { "expr": "ram_evictions_total_bytes{}", "legendFormat": "{{__name__}}" },
    { "expr": "ram_evictions_used_perc{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "RAM Evictions Timer",
   "type": "graph",
   "gridPos": { "h": 11, "w": 3, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"ram_evictions_timer_sum\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{__name__=~\"ram_evictions\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Storage Closing Timers",
   "type": "graph",
   "description": "They only show up once the server is stopped",
   "gridPos": { "h": 11, "w": 3, "x": 15, "y": 22 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"storage_caches_flush_timer_sum\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{__name__=~\"storage_badger_close_timer_sum\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}