{
 "title": "Pyroscope v2 / Read Path",
 "tags": [
  "pyroscope",
  "pyroscope-v2"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "metrics", "query": "prometheus" },
   { "name": "loki_datasource", "label": "logs", "query": "loki" },
   { "name": "tempo_datasource", "label": "traces", "query": "tempo" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(pyroscope_build_info{namespace=\"$namespace\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(pyroscope_build_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Query Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Queries",
     "type": "table",
     "description": "SelectMergeProfile filtered out by default as the API is used by Canary Exporter",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=~\"$namespace\",cluster=~\"$cluster\",container=\"query-frontend\"}\n|= \"route=/querier.v1.\"\n| logfmt | line_format \"tenant={{.orgID}} status={{.status}}  duration={{.duration}} traceID={{.traceID}} {{.uri}}\""
      }
     ]
    },
    {
     "title": "Traces",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "filters": [
        {
         "id": "d5be7410",
         "operator": "=",
         "scope": "resource",
         "tag": "k8s.namespace.name",
         "value": [ "$namespace" ],
         "valueType": "string"
        },
        {
         "id": "service-name",
         "operator": "=",
         "scope": "resource",
         "tag": "service.name",
         "value": [
          "pyroscope-query-frontend",
          "pyroscope-query-backend"
         ],
         "valueType": "string"
        },
        {
         "id": "min-duration",
         "operator": ">",
         "tag": "duration",
         "value": "100ms",
         "valueType": "duration"
        },
        {
         "id": "span-name",
         "operator": "!=",
         "scope": "span",
         "tag": "name",
         "value": [ "HTTP GET - debug_pprof" ],
         "valueType": "string"
        }
       ],
       "limit": 25,
       "metricsQueryType": "instant",
       "spss": 5,
       "tableType": "traces"
      }
     ]
    }
   ]
  },
  {
   "title": "Metadata Query Service (metastore)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Raft Nodes",
   "type": "state-timeline",
   "description": "Raft node roles observed by each node. The view is not meant to be 100% consistent, and only serves monitoring purposes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  pyroscope_metastore_raft_state{namespace=\"$namespace\",state=\"Follower\"} or\n  pyroscope_metastore_raft_state{namespace=\"$namespace\",state=\"Leader\"} * 100\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "QueryMetadata Latency",
   "type": "timeseries",
   "description": "The latency of QueryMetadata endpoint observed by metastore nodes.\n\nThe only user is the query-frontend service.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(pyroscope_request_duration_seconds{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.MetadataQueryService/QueryMetadata\",\n}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(pyroscope_request_duration_seconds{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.MetadataQueryService/QueryMetadata\",\n}[$__rate_interval])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "QueryMetadataLabels Latency",
   "type": "timeseries",
   "description": "The latency of QueryMetadataLabels endpoint observed by metastore nodes.\n\nThe only user is the query-frontend service.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(pyroscope_request_duration_seconds{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.MetadataQueryService/QueryMetadataLabels\",\n}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(pyroscope_request_duration_seconds{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.MetadataQueryService/QueryMetadataLabels\",\n}[$__rate_interval])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Snapshot Size",
   "type": "timeseries",
   "description": "The size of BoltDB snapshot taken by FSM",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pyroscope_metastore_boltdb_persist_snapshot_size_bytes{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(histogram_count(irate(pyroscope_request_duration_seconds{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.MetadataQueryService/QueryMetadata\",\n}[$__rate_interval]))) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(histogram_count(irate(pyroscope_request_duration_seconds{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/metastore.v1.MetadataQueryService/QueryMetadataLabels\",\n}[$__rate_interval]))) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Query Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Query rate",
   "type": "timeseries",
   "description": "Query rate observed by cortex-gw",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status_code) (histogram_count(rate(pyroscope_request_duration_seconds{cluster=~\"$cluster\", container=~\"pyroscope|distributor|query-frontend\", namespace=~\"$namespace\", route=~\".*pyroscope_render.*|.*pyroscope_label.*|.*querierservice.*\"}[5m])))",
     "legendFormat": "{{status_code}} "
    }
   ]
  },
  {
   "title": "Query Duartion",
   "type": "timeseries",
   "description": "Query duration observed by cortex-gw",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (route) ( rate(pyroscope_request_duration_seconds{container=~\"pyroscope|distributor|query-frontend\", namespace=~\"$namespace\", cluster=~\"$cluster\",route=~\".*pyroscope_render.*|.*pyroscope_label.*|.*querierservice.*\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Query Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Invocations",
   "type": "timeseries",
   "description": "Number of query-backend invocations.\n\nErrors are expected: usually those indicate that the query is throttled with the concurrency limiter.\n\nIf errors are presents in the query-frontend/gateway, the query is failed.\n",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(histogram_count(irate(pyroscope_request_duration_seconds{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/query.v1.QueryBackendService/Invoke\",\n}[$__rate_interval]))) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invocation Duration",
   "type": "timeseries",
   "description": "QueryBackend.Invoke latency observed by query-backend instances",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(pyroscope_request_duration_seconds{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/query.v1.QueryBackendService/Invoke\",\n}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(pyroscope_request_duration_seconds{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/query.v1.QueryBackendService/Invoke\",\n}[$__rate_interval])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Heatmap",
   "type": "heatmap",
   "description": "QueryBackend.Invokeduration observed by query-backend instances",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum (rate(pyroscope_request_duration_seconds{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/query.v1.QueryBackendService/Invoke\",\n  status_code=\"success\"\n}[$__rate_interval]))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(pyroscope_request_duration_seconds{\n  namespace=\"$namespace\",\n  method=\"gRPC\",\n  route=\"/query.v1.QueryBackendService/Invoke\",\n}[$__rate_interval])) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"query-backend\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_requests{job=~\"(.*/)?kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\".*-query-backend\"}\n)",
     "legendFormat": "Request"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_limits{job=~\"(.*/)?kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\".*-query-backend\"}\n)",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU Usage (stack)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"query-backend\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"query-backend\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\",container=\"query-backend\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"query-backend\", image!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",container=\"query-backend\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "max (kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\",container=\"query-backend\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Storage I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(operation) (irate(objstore_bucket_operations_total{namespace=\"$namespace\",container=\"query-backend\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total{job=~\"(.*/)?cadvisor\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]) * on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*query-backend.*\"}) by (namespace,pod)) * -1",
     "legendFormat": "tx {{pod}}"
    },
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{job=~\"(.*/)?cadvisor\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]) * on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\".*query-backend.*\"}) by (namespace,pod))",
     "legendFormat": "rx {{pod}}"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go Threads",
     "type": "timeseries",
     "description": "Number of OS threads created",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_threads{namespace=\"$namespace\",container=\"query-backend\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (go_goroutines{namespace=\"$namespace\",container=\"query-backend\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap In-Use",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (go_memstats_heap_inuse_bytes{namespace=\"$namespace\",container=\"query-backend\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 155 },
     "targets": [
      {
       "expr": "sum by (pod) (container_file_descriptors{namespace=\"$namespace\",container=\"query-backend\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors and warnings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Worker log",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 156 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", container=\"query-backend\"} |= \"level=err\" or \"level=warn\" or \"panic\""
      }
     ]
    }
   ]
  }
 ]
}