#!/usr/bin/env bash

DOCKER_ARGS="--net=host"

if [[ $OSTYPE == 'darwin'* ]]; then
    FIRE_URL=${FIRE_URL:-http://docker.for.mac.localhost:4100}
    DOCKER_ARGS=""
else
    FIRE_URL=${FIRE_URL:-http://localhost:4100}
fi

PYRO_URL=$FIRE_URL/pyroscope
PROMETHEUS_URL=$FIRE_URL/prometheus

datasource_provisioning="$(mktemp "${TMPDIR:-/tmp}/fire-provisioning-XXXXXX")"
chmod 0644 "${datasource_provisioning}"
trap 'rm -f "${datasource_provisioning}"' EXIT
cat > "${datasource_provisioning}" <<EOF
apiVersion: 1
datasources:
  - name: Fire-Pyroscope
    type: pyroscope-datasource
    jsonData:
      path: ${PYRO_URL}
  - name: Prometheus
    type: prometheus
    url: ${PROMETHEUS_URL}
  - name: Fire
    type: grafana-fire-datasource
    url: ${FIRE_URL}
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "anonymous"
EOF

docker run $DOCKER_ARGS --rm \
  --name fire-grafana \
  -v "${datasource_provisioning}:/etc/grafana/provisioning/datasources/fire.yaml:ro" \
  -v "$(pwd)"/grafana/fire-datasource/dist:/var/lib/grafana/plugins/fire-datasource \
  -v "$(pwd)"/grafana/flamegraph/dist:/var/lib/grafana/plugins/flamegraph \
  -e GF_INSTALL_PLUGINS=pyroscope-datasource,pyroscope-panel \
  -e GF_DEFAULT_APP_MODE=development \
  -e GF_AUTH_ANONYMOUS_ENABLED=true \
  -e GF_AUTH_ANONYMOUS_ORG_ROLE=Admin \
  -t -i -p 3000:3000 aocenas/grafana:explore-experiment-2
