{
 "title": "Pyroscope Raw Metrics Comparison",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cpu_utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "targets": [
    { "expr": "cpu_utilization" }
   ]
  },
  { "title": "Cache Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "cache_trees_size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 12 },
   "targets": [
    { "expr": "cache_trees_size" }
   ]
  },
  {
   "title": "cache_dicts_size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 12 },
   "targets": [
    { "expr": "cache_dicts_size" }
   ]
  },
  {
   "title": "cache_segments_size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 12 },
   "targets": [
    { "expr": "cache_segments_size" }
   ]
  },
  {
   "title": "cache_dimensions_size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 12 },
   "targets": [
    { "expr": "cache_dimensions_size" }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "disk_dimensions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 23 },
   "targets": [
    { "expr": "disk_dimensions" }
   ]
  },
  {
   "title": "disk_dicts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 23 },
   "targets": [
    { "expr": "disk_dicts" }
   ]
  },
  {
   "title": "disk_trees",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 23 },
   "targets": [
    { "expr": "disk_trees" }
   ]
  },
  {
   "title": "disk_segments",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 23 },
   "targets": [
    { "expr": "disk_segments" }
   ]
  },
  {
   "title": "disk_main",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 33 },
   "targets": [
    { "expr": "disk_main" }
   ]
  },
  {
   "title": "disk_local_profiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 33 },
   "targets": [
    { "expr": "disk_local_profiles" }
   ]
  },
  { "title": "Timers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "retention_timer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 44 },
   "targets": [
    { "expr": "retention_timer" }
   ]
  },
  {
   "title": "write_back_timer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 44 },
   "targets": [
    { "expr": "write_back_timer" }
   ]
  },
  {
   "title": "evictions_timer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 44 },
   "targets": [
    { "expr": "evictions_timer" }
   ]
  },
  {
   "title": "storage_badger_close_timer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 44 },
   "targets": [
    { "expr": "storage_badger_close_timer" }
   ]
  },
  {
   "title": "storage_caches_flush_timer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 54 },
   "targets": [
    { "expr": "storage_caches_flush_timer" }
   ]
  },
  { "title": "evictions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "evictions_used_perc",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 65 },
   "targets": [
    { "expr": "evictions_used_perc" }
   ]
  },
  {
   "title": "evictions_total_bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 65 },
   "targets": [
    { "expr": "evictions_total_bytes" }
   ]
  },
  {
   "title": "evictions_alloc_bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 65 },
   "targets": [
    { "expr": "evictions_alloc_bytes" }
   ]
  },
  { "title": "storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "storage_reads_total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 76 },
   "targets": [
    { "expr": "storage_reads_total" }
   ]
  },
  {
   "title": "retention_count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 76 },
   "targets": [
    { "expr": "retention_count" }
   ]
  },
  {
   "title": "evictions_count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 76 },
   "targets": [
    { "expr": "evictions_count" }
   ]
  },
  {
   "title": "write_back_count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 76 },
   "targets": [
    { "expr": "write_back_count" }
   ]
  },
  {
   "title": "storage_writes_total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 86 },
   "targets": [
    { "expr": "storage_writes_total" }
   ]
  },
  {
   "title": "successful_uploads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 86 },
   "targets": [
    { "expr": "successful_uploads" }
   ]
  },
  {
   "title": "upload_errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 86 },
   "targets": [
    { "expr": "upload_errors" }
   ]
  }
 ]
}