// Code generated by mockery. DO NOT EDIT.

package mockclient

import (
	context "context"

	github "github.com/google/go-github/v58/github"
	mock "github.com/stretchr/testify/mock"
)

// MockrepositoryService is an autogenerated mock type for the repositoryService type
type MockrepositoryService struct {
	mock.Mock
}

type MockrepositoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockrepositoryService) EXPECT() *MockrepositoryService_Expecter {
	return &MockrepositoryService_Expecter{mock: &_m.Mock}
}

// GetCommit provides a mock function with given fields: ctx, owner, repo, ref, opts
func (_m *MockrepositoryService) GetCommit(ctx context.Context, owner string, repo string, ref string, opts *github.ListOptions) (*github.RepositoryCommit, *github.Response, error) {
	ret := _m.Called(ctx, owner, repo, ref, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetCommit")
	}

	var r0 *github.RepositoryCommit
	var r1 *github.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *github.ListOptions) (*github.RepositoryCommit, *github.Response, error)); ok {
		return rf(ctx, owner, repo, ref, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *github.ListOptions) *github.RepositoryCommit); ok {
		r0 = rf(ctx, owner, repo, ref, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.RepositoryCommit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *github.ListOptions) *github.Response); ok {
		r1 = rf(ctx, owner, repo, ref, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, *github.ListOptions) error); ok {
		r2 = rf(ctx, owner, repo, ref, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockrepositoryService_GetCommit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommit'
type MockrepositoryService_GetCommit_Call struct {
	*mock.Call
}

// GetCommit is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - ref string
//   - opts *github.ListOptions
func (_e *MockrepositoryService_Expecter) GetCommit(ctx interface{}, owner interface{}, repo interface{}, ref interface{}, opts interface{}) *MockrepositoryService_GetCommit_Call {
	return &MockrepositoryService_GetCommit_Call{Call: _e.mock.On("GetCommit", ctx, owner, repo, ref, opts)}
}

func (_c *MockrepositoryService_GetCommit_Call) Run(run func(ctx context.Context, owner string, repo string, ref string, opts *github.ListOptions)) *MockrepositoryService_GetCommit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*github.ListOptions))
	})
	return _c
}

func (_c *MockrepositoryService_GetCommit_Call) Return(_a0 *github.RepositoryCommit, _a1 *github.Response, _a2 error) *MockrepositoryService_GetCommit_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockrepositoryService_GetCommit_Call) RunAndReturn(run func(context.Context, string, string, string, *github.ListOptions) (*github.RepositoryCommit, *github.Response, error)) *MockrepositoryService_GetCommit_Call {
	_c.Call.Return(run)
	return _c
}

// GetContents provides a mock function with given fields: ctx, owner, repo, path, opts
func (_m *MockrepositoryService) GetContents(ctx context.Context, owner string, repo string, path string, opts *github.RepositoryContentGetOptions) (*github.RepositoryContent, []*github.RepositoryContent, *github.Response, error) {
	ret := _m.Called(ctx, owner, repo, path, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetContents")
	}

	var r0 *github.RepositoryContent
	var r1 []*github.RepositoryContent
	var r2 *github.Response
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *github.RepositoryContentGetOptions) (*github.RepositoryContent, []*github.RepositoryContent, *github.Response, error)); ok {
		return rf(ctx, owner, repo, path, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *github.RepositoryContentGetOptions) *github.RepositoryContent); ok {
		r0 = rf(ctx, owner, repo, path, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.RepositoryContent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *github.RepositoryContentGetOptions) []*github.RepositoryContent); ok {
		r1 = rf(ctx, owner, repo, path, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*github.RepositoryContent)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, *github.RepositoryContentGetOptions) *github.Response); ok {
		r2 = rf(ctx, owner, repo, path, opts)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*github.Response)
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, string, string, *github.RepositoryContentGetOptions) error); ok {
		r3 = rf(ctx, owner, repo, path, opts)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockrepositoryService_GetContents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContents'
type MockrepositoryService_GetContents_Call struct {
	*mock.Call
}

// GetContents is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - path string
//   - opts *github.RepositoryContentGetOptions
func (_e *MockrepositoryService_Expecter) GetContents(ctx interface{}, owner interface{}, repo interface{}, path interface{}, opts interface{}) *MockrepositoryService_GetContents_Call {
	return &MockrepositoryService_GetContents_Call{Call: _e.mock.On("GetContents", ctx, owner, repo, path, opts)}
}

func (_c *MockrepositoryService_GetContents_Call) Run(run func(ctx context.Context, owner string, repo string, path string, opts *github.RepositoryContentGetOptions)) *MockrepositoryService_GetContents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*github.RepositoryContentGetOptions))
	})
	return _c
}

func (_c *MockrepositoryService_GetContents_Call) Return(_a0 *github.RepositoryContent, _a1 []*github.RepositoryContent, _a2 *github.Response, _a3 error) *MockrepositoryService_GetContents_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockrepositoryService_GetContents_Call) RunAndReturn(run func(context.Context, string, string, string, *github.RepositoryContentGetOptions) (*github.RepositoryContent, []*github.RepositoryContent, *github.Response, error)) *MockrepositoryService_GetContents_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockrepositoryService creates a new instance of MockrepositoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockrepositoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockrepositoryService {
	mock := &MockrepositoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
