name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "v*"

permissions:
  contents: write
  packages: write
  id-token: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-x64-large
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
          persist-credentials: 'false'
      - name: Set GIT_LAST_COMMIT_DATE
        run: echo "GIT_LAST_COMMIT_DATE=$(git log -1 --date=iso-strict --format=%cd)" >> $GITHUB_ENV
      - name: Set IMAGE_TAG from git tag
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Set IMAGE_PUBLISH_LATEST=true, so we overwrite the latest docker image tag and update Homebrew
        run: echo "IMAGE_PUBLISH_LATEST=true" >> $GITHUB_ENV
      # Forces goreleaser to use the correct previous tag for the changelog
      - name: Set GORELEASER_PREVIOUS_TAG
        run: echo "GORELEASER_PREVIOUS_TAG=$(git tag -l --sort=-version:refname | grep -E '^v.*' | head -n 2 | tail -1)" >> $GITHUB_ENV
      - run: git fetch --force --tags
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: "1.25.10"
          cache: false
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 20
          package-manager-cache: false
      # setup docker buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      - name: Log into GAR
        uses: grafana/shared-workflows/actions/login-to-gar@c7ad5f57693ac858c698d95783685a9cbfd91223 # login-to-gar/v1.0.1
        with:
          registry: us-docker.pkg.dev
      - id: get-github-app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@580590a644e82e79bb2598bdaba0be245a14dda0 # create-github-app-token/v0.2.2
        with:
          github_app: grafana-pyroscope-bot
      - run: make frontend/build
      - uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7.2.2
        with:
          # ensure this aligns with the version specified in the /Makefile
          version: v2.13.2
          args: release --clean --timeout 60m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ github.ref_name }}
      # make generate-formulas expects PYROSCOPE_TAG to be set
      - name: Set PYROSCOPE_TAG
        run: echo "PYROSCOPE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      # Our Homebrew publishing currently assumes latest releases only
      - if: env.IMAGE_PUBLISH_LATEST == 'true'
        name: Update homebrew formulas
        run: |
          git config --global url."https://x-access-token:$(echo "${HOMEBREW_GITHUB_TOKEN}" | xargs)@github.com/grafana/homebrew-pyroscope".insteadOf "https://github.com/grafana/homebrew-pyroscope" 2> /dev/null
          git config --global user.email "dmitry+bot@pyroscope.io"
          git config --global user.name "Pyroscope Bot <dmitry+bot@pyroscope.io>"
          git clone https://github.com/grafana/homebrew-pyroscope ../homebrew-pyroscope
          cd ../homebrew-pyroscope
          make generate-formulas && git add Formula && git commit -m "chore: update formulas" && git push origin main
        env:
          HOMEBREW_GITHUB_TOKEN: ${{ steps.get-github-app-token.outputs.token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
