package ebpfspy

import (
	"fmt"
	"io"
	"regexp"
	"strconv"

	"github.com/pkg/errors"
)

type PythonVersion struct {
	Major, Minor, Patch int
}

func (p *PythonVersion) Compare(other PythonVersion) int {
	major := p.Major - other.Major
	if major != 0 {
		return major
	}

	minor := p.Minor - other.Minor
	if minor != 0 {
		return minor
	}
	return p.Patch - other.Patch
}

// GetPythonPatchVersion searches for a patch version given a major + minor version with regexp
// r is libpython3.11.so or python3.11 elf binary
func GetPythonPatchVersion(r io.Reader, v PythonVersion) (PythonVersion, error) {
	rePythonVersion := regexp.MustCompile(fmt.Sprintf("%d\\.%d\\.(\\d+)[^\\d]", v.Major, v.Minor))
	res := v
	res.Patch = 0
	submatch, err := rgrep(r, rePythonVersion)
	if err != nil {
		return res, fmt.Errorf("rgrep python version %v %w", v, err)
	}
	patch, err := strconv.Atoi(string(submatch[1]))
	if err != nil {
		return res, fmt.Errorf("error trying to grep python patch version %s, %w", string(submatch[0]), err)
	}
	res.Patch = patch
	return res, nil
}

var reMuslVersion = regexp.MustCompile("1\\.([12])\\.(\\d+)\\D")

func GetMuslVersion(r io.Reader) (int, error) {
	submatch, err := rgrep(r, reMuslVersion)
	if err != nil {
		return 0, fmt.Errorf("rgrep python version  %w", err)
	}
	fmt.Println(string(submatch[0]))
	minor, err := strconv.Atoi(string(submatch[1]))
	if err != nil {
		return 0, fmt.Errorf("error trying to grep musl minor version %s, %w", string(submatch[0]), err)
	}
	patch, err := strconv.Atoi(string(submatch[2]))
	if err != nil {
		return 0, fmt.Errorf("error trying to grep musl patch version %s, %w", string(submatch[0]), err)
	}
	if minor == 1 {
		return 1, nil
	}
	if patch <= 4 {
		return 2, nil
	}
	//return 0, fmt.Errorf("untested musl version %s", string(submatch[0][0]))
	return 2, nil // let's hope it won't change in patch fix
}

func rgrep(r io.Reader, re *regexp.Regexp) ([][]byte, error) {
	const bufSize = 0x1000
	const lookBack = 0x10
	buf := make([]byte, bufSize+lookBack)
	for {
		n, err := r.Read(buf[lookBack:])
		if n > 0 {
			it := buf[:lookBack+n]
			submatch := re.FindSubmatch(it)
			if submatch != nil {
				return submatch, nil
			}
			copy(buf[:lookBack], it[len(it)-lookBack:len(it)])
		}
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			return nil, fmt.Errorf("error trying to grep python patch version %w", err)
		}
	}
	return nil, fmt.Errorf("rgrep not found %v", re.String())
}

type userPyOffsetConfig struct {
	PyObjectObType                 int64
	PyTypeObjectTpName             int64
	PyThreadStateFrame             int64
	PyFrameObjectF_back            int64
	PyFrameObjectF_code            int64
	PyFrameObjectF_frame           int64
	PyFrameObjectF_localsplus      int64
	PyCodeObjectCoFilename         int64
	PyCodeObjectCoName             int64
	PyCodeObjectCoVarnames         int64
	PyTupleObjectObItem            int64
	PyInterpreterFrameF_code       int64
	PyRuntimeStateGilstate         int64
	GilstateRuntimeStateAutoTSSkey int64
	PyTssT_key                     int64
	StringSize                     int64
}

var pyVersions = map[PythonVersion]userPyOffsetConfig{
	// 3.5.0 /home/korniltsev/mygithub/dbudy/dwarfdump239/python35/python/3.5.0/lib/libpython3.5m.so.1.0
	PythonVersion{3, 5, 0}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.5.1 /home/korniltsev/mygithub/dbudy/dwarfdump239/python35/python/3.5.1/lib/libpython3.5m.so.1.0
	PythonVersion{3, 5, 1}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.5.2 /home/korniltsev/mygithub/dbudy/dwarfdump239/python35/python/3.5.2/lib/libpython3.5m.so.1.0
	PythonVersion{3, 5, 2}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.5.3 /home/korniltsev/mygithub/dbudy/dwarfdump239/python35/python/3.5.3/lib/libpython3.5m.so.1.0
	PythonVersion{3, 5, 3}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.5.4 /home/korniltsev/mygithub/dbudy/dwarfdump239/python35/python/3.5.4/lib/libpython3.5m.so.1.0
	PythonVersion{3, 5, 4}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.5.5 /home/korniltsev/mygithub/dbudy/dwarfdump239/python35/python/3.5.5/lib/libpython3.5m.so.1.0
	PythonVersion{3, 5, 5}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.5.6 /home/korniltsev/mygithub/dbudy/dwarfdump239/python35/python/3.5.6/lib/libpython3.5m.so.1.0
	PythonVersion{3, 5, 6}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.5.7 /home/korniltsev/mygithub/dbudy/dwarfdump239/python35/python/3.5.7/lib/libpython3.5m.so.1.0
	PythonVersion{3, 5, 7}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.5.8 /home/korniltsev/mygithub/dbudy/dwarfdump239/python35/python/3.5.8/lib/libpython3.5m.so.1.0
	PythonVersion{3, 5, 8}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.5.9 /home/korniltsev/mygithub/dbudy/dwarfdump239/python35/python/3.5.9/lib/libpython3.5m.so.1.0
	PythonVersion{3, 5, 9}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.5.10 /home/korniltsev/mygithub/dbudy/dwarfdump239/python35/python/3.5.10/lib/libpython3.5m.so.1.0
	PythonVersion{3, 5, 10}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.6.0 /home/korniltsev/.asdf/installs/python/3.6.0/lib/libpython3.6m.so.1.0
	PythonVersion{3, 6, 0}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.6.1 /home/korniltsev/.asdf/installs/python/3.6.1/lib/libpython3.6m.so.1.0
	PythonVersion{3, 6, 1}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.6.2 /home/korniltsev/.asdf/installs/python/3.6.2/lib/libpython3.6m.so.1.0
	PythonVersion{3, 6, 2}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.6.3 /home/korniltsev/.asdf/installs/python/3.6.3/lib/libpython3.6m.so.1.0
	PythonVersion{3, 6, 3}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.6.4 /home/korniltsev/.asdf/installs/python/3.6.4/lib/libpython3.6m.so.1.0
	PythonVersion{3, 6, 4}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.6.5 /home/korniltsev/.asdf/installs/python/3.6.5/lib/libpython3.6m.so.1.0
	PythonVersion{3, 6, 5}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.6.6 /home/korniltsev/.asdf/installs/python/3.6.6/lib/libpython3.6m.so.1.0
	PythonVersion{3, 6, 6}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.6.7 /home/korniltsev/.asdf/installs/python/3.6.7/lib/libpython3.6m.so.1.0
	PythonVersion{3, 6, 7}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.6.8 /home/korniltsev/.asdf/installs/python/3.6.8/lib/libpython3.6m.so.1.0
	PythonVersion{3, 6, 8}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.6.9 /home/korniltsev/.asdf/installs/python/3.6.9/lib/libpython3.6m.so.1.0
	PythonVersion{3, 6, 9}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.6.10 /home/korniltsev/.asdf/installs/python/3.6.10/lib/libpython3.6m.so.1.0
	PythonVersion{3, 6, 10}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.6.11 /home/korniltsev/.asdf/installs/python/3.6.11/lib/libpython3.6m.so.1.0
	PythonVersion{3, 6, 11}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.6.12 /home/korniltsev/.asdf/installs/python/3.6.12/lib/libpython3.6m.so.1.0
	PythonVersion{3, 6, 12}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.6.13 /home/korniltsev/.asdf/installs/python/3.6.13/lib/libpython3.6m.so.1.0
	PythonVersion{3, 6, 13}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.6.14 /home/korniltsev/.asdf/installs/python/3.6.14/lib/libpython3.6m.so.1.0
	PythonVersion{3, 6, 14}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.6.15 /home/korniltsev/.asdf/installs/python/3.6.15/lib/libpython3.6m.so.1.0
	PythonVersion{3, 6, 15}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      376,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         -1,
		GilstateRuntimeStateAutoTSSkey: -1,
		PyTssT_key:                     -1,
		StringSize:                     48,
	},
	// 3.7.0 /home/korniltsev/.asdf/installs/python/3.7.0/lib/libpython3.7m.so.1.0
	PythonVersion{3, 7, 0}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1384,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.7.1 /home/korniltsev/.asdf/installs/python/3.7.1/lib/libpython3.7m.so.1.0
	PythonVersion{3, 7, 1}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1384,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.7.2 /home/korniltsev/.asdf/installs/python/3.7.2/lib/libpython3.7m.so.1.0
	PythonVersion{3, 7, 2}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1384,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.7.3 /home/korniltsev/.asdf/installs/python/3.7.3/lib/libpython3.7m.so.1.0
	PythonVersion{3, 7, 3}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1384,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.7.4 /home/korniltsev/.asdf/installs/python/3.7.4/lib/libpython3.7m.so.1.0
	PythonVersion{3, 7, 4}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1472,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.7.5 /home/korniltsev/.asdf/installs/python/3.7.5/lib/libpython3.7m.so.1.0
	PythonVersion{3, 7, 5}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1472,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.7.6 /home/korniltsev/.asdf/installs/python/3.7.6/lib/libpython3.7m.so.1.0
	PythonVersion{3, 7, 6}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1472,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.7.7 /home/korniltsev/.asdf/installs/python/3.7.7/lib/libpython3.7m.so.1.0
	PythonVersion{3, 7, 7}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1472,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.7.8 /home/korniltsev/.asdf/installs/python/3.7.8/lib/libpython3.7m.so.1.0
	PythonVersion{3, 7, 8}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1472,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.7.9 /home/korniltsev/.asdf/installs/python/3.7.9/lib/libpython3.7m.so.1.0
	PythonVersion{3, 7, 9}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1472,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.7.10 /home/korniltsev/.asdf/installs/python/3.7.10/lib/libpython3.7m.so.1.0
	PythonVersion{3, 7, 10}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1472,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.7.11 /home/korniltsev/.asdf/installs/python/3.7.11/lib/libpython3.7m.so.1.0
	PythonVersion{3, 7, 11}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1472,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.7.12 /home/korniltsev/.asdf/installs/python/3.7.12/lib/libpython3.7m.so.1.0
	PythonVersion{3, 7, 12}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1472,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.7.13 /home/korniltsev/.asdf/installs/python/3.7.13/lib/libpython3.7m.so.1.0
	PythonVersion{3, 7, 13}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1472,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.7.14 /home/korniltsev/.asdf/installs/python/3.7.14/lib/libpython3.7m.so.1.0
	PythonVersion{3, 7, 14}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1472,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.7.15 /home/korniltsev/.asdf/installs/python/3.7.15/lib/libpython3.7m.so.1.0
	PythonVersion{3, 7, 15}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1472,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.7.16 /home/korniltsev/.asdf/installs/python/3.7.16/lib/libpython3.7m.so.1.0
	PythonVersion{3, 7, 16}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1472,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.7.17 /home/korniltsev/.asdf/installs/python/3.7.17/lib/libpython3.7m.so.1.0
	PythonVersion{3, 7, 17}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         96,
		PyCodeObjectCoName:             104,
		PyCodeObjectCoVarnames:         64,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1472,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.8.0 /home/korniltsev/.asdf/installs/python/3.8.0/lib/libpython3.8.so.1.0
	PythonVersion{3, 8, 0}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1360,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.8.1 /home/korniltsev/.asdf/installs/python/3.8.1/lib/libpython3.8.so.1.0
	PythonVersion{3, 8, 1}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1360,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.8.2 /home/korniltsev/.asdf/installs/python/3.8.2/lib/libpython3.8.so.1.0
	PythonVersion{3, 8, 2}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1360,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.8.3 /home/korniltsev/.asdf/installs/python/3.8.3/lib/libpython3.8.so.1.0
	PythonVersion{3, 8, 3}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1360,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.8.4 /home/korniltsev/.asdf/installs/python/3.8.4/lib/libpython3.8.so.1.0
	PythonVersion{3, 8, 4}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1360,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.8.5 /home/korniltsev/.asdf/installs/python/3.8.5/lib/libpython3.8.so.1.0
	PythonVersion{3, 8, 5}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1360,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.8.6 /home/korniltsev/.asdf/installs/python/3.8.6/lib/libpython3.8.so.1.0
	PythonVersion{3, 8, 6}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1360,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.8.7 /home/korniltsev/.asdf/installs/python/3.8.7/lib/libpython3.8.so.1.0
	PythonVersion{3, 8, 7}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1360,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.8.8 /home/korniltsev/.asdf/installs/python/3.8.8/lib/libpython3.8.so.1.0
	PythonVersion{3, 8, 8}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1360,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.8.9 /home/korniltsev/.asdf/installs/python/3.8.9/lib/libpython3.8.so.1.0
	PythonVersion{3, 8, 9}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1360,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.8.10 /home/korniltsev/.asdf/installs/python/3.8.10/lib/libpython3.8.so.1.0
	PythonVersion{3, 8, 10}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1360,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.8.11 /home/korniltsev/.asdf/installs/python/3.8.11/lib/libpython3.8.so.1.0
	PythonVersion{3, 8, 11}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1360,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.8.12 /home/korniltsev/.asdf/installs/python/3.8.12/lib/libpython3.8.so.1.0
	PythonVersion{3, 8, 12}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1360,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.8.13 /home/korniltsev/.asdf/installs/python/3.8.13/lib/libpython3.8.so.1.0
	PythonVersion{3, 8, 13}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1360,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.8.14 /home/korniltsev/.asdf/installs/python/3.8.14/lib/libpython3.8.so.1.0
	PythonVersion{3, 8, 14}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1360,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.8.15 /home/korniltsev/.asdf/installs/python/3.8.15/lib/libpython3.8.so.1.0
	PythonVersion{3, 8, 15}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1360,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.8.16 /home/korniltsev/.asdf/installs/python/3.8.16/lib/libpython3.8.so.1.0
	PythonVersion{3, 8, 16}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1360,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.8.17 /home/korniltsev/.asdf/installs/python/3.8.17/lib/libpython3.8.so.1.0
	PythonVersion{3, 8, 17}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         1360,
		GilstateRuntimeStateAutoTSSkey: 32,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.9.0 /home/korniltsev/.asdf/installs/python/3.9.0/lib/libpython3.9.so.1.0
	PythonVersion{3, 9, 0}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.9.1 /home/korniltsev/.asdf/installs/python/3.9.1/lib/libpython3.9.so.1.0
	PythonVersion{3, 9, 1}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.9.2 /home/korniltsev/.asdf/installs/python/3.9.2/lib/libpython3.9.so.1.0
	PythonVersion{3, 9, 2}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.9.4 /home/korniltsev/.asdf/installs/python/3.9.4/lib/libpython3.9.so.1.0
	PythonVersion{3, 9, 4}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.9.5 /home/korniltsev/.asdf/installs/python/3.9.5/lib/libpython3.9.so.1.0
	PythonVersion{3, 9, 5}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.9.6 /home/korniltsev/.asdf/installs/python/3.9.6/lib/libpython3.9.so.1.0
	PythonVersion{3, 9, 6}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.9.7 /home/korniltsev/.asdf/installs/python/3.9.7/lib/libpython3.9.so.1.0
	PythonVersion{3, 9, 7}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.9.8 /home/korniltsev/.asdf/installs/python/3.9.8/lib/libpython3.9.so.1.0
	PythonVersion{3, 9, 8}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.9.9 /home/korniltsev/.asdf/installs/python/3.9.9/lib/libpython3.9.so.1.0
	PythonVersion{3, 9, 9}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.9.10 /home/korniltsev/.asdf/installs/python/3.9.10/lib/libpython3.9.so.1.0
	PythonVersion{3, 9, 10}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.9.11 /home/korniltsev/.asdf/installs/python/3.9.11/lib/libpython3.9.so.1.0
	PythonVersion{3, 9, 11}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.9.12 /home/korniltsev/.asdf/installs/python/3.9.12/lib/libpython3.9.so.1.0
	PythonVersion{3, 9, 12}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.9.13 /home/korniltsev/.asdf/installs/python/3.9.13/lib/libpython3.9.so.1.0
	PythonVersion{3, 9, 13}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.9.14 /home/korniltsev/.asdf/installs/python/3.9.14/lib/libpython3.9.so.1.0
	PythonVersion{3, 9, 14}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.9.15 /home/korniltsev/.asdf/installs/python/3.9.15/lib/libpython3.9.so.1.0
	PythonVersion{3, 9, 15}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.9.16 /home/korniltsev/.asdf/installs/python/3.9.16/lib/libpython3.9.so.1.0
	PythonVersion{3, 9, 16}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.9.17 /home/korniltsev/.asdf/installs/python/3.9.17/lib/libpython3.9.so.1.0
	PythonVersion{3, 9, 17}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      360,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.10.0 /home/korniltsev/.asdf/installs/python/3.10.0/lib/libpython3.10.so.1.0
	PythonVersion{3, 10, 0}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      352,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.10.1 /home/korniltsev/.asdf/installs/python/3.10.1/lib/libpython3.10.so.1.0
	PythonVersion{3, 10, 1}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      352,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.10.2 /home/korniltsev/.asdf/installs/python/3.10.2/lib/libpython3.10.so.1.0
	PythonVersion{3, 10, 2}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      352,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.10.3 /home/korniltsev/.asdf/installs/python/3.10.3/lib/libpython3.10.so.1.0
	PythonVersion{3, 10, 3}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      352,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.10.4 /home/korniltsev/.asdf/installs/python/3.10.4/lib/libpython3.10.so.1.0
	PythonVersion{3, 10, 4}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      352,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.10.5 /home/korniltsev/.asdf/installs/python/3.10.5/lib/libpython3.10.so.1.0
	PythonVersion{3, 10, 5}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      352,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.10.6 /home/korniltsev/.asdf/installs/python/3.10.6/lib/libpython3.10.so.1.0
	PythonVersion{3, 10, 6}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      352,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.10.7 /home/korniltsev/.asdf/installs/python/3.10.7/lib/libpython3.10.so.1.0
	PythonVersion{3, 10, 7}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      352,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.10.8 /home/korniltsev/.asdf/installs/python/3.10.8/lib/libpython3.10.so.1.0
	PythonVersion{3, 10, 8}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      352,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.10.9 /home/korniltsev/.asdf/installs/python/3.10.9/lib/libpython3.10.so.1.0
	PythonVersion{3, 10, 9}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      352,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.10.10 /home/korniltsev/.asdf/installs/python/3.10.10/lib/libpython3.10.so.1.0
	PythonVersion{3, 10, 10}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      352,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.10.11 /home/korniltsev/.asdf/installs/python/3.10.11/lib/libpython3.10.so.1.0
	PythonVersion{3, 10, 11}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      352,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.10.12 /home/korniltsev/.asdf/installs/python/3.10.12/lib/libpython3.10.so.1.0
	PythonVersion{3, 10, 12}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             24,
		PyFrameObjectF_back:            24,
		PyFrameObjectF_code:            32,
		PyFrameObjectF_frame:           -1,
		PyFrameObjectF_localsplus:      352,
		PyCodeObjectCoFilename:         104,
		PyCodeObjectCoName:             112,
		PyCodeObjectCoVarnames:         72,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       -1,
		PyRuntimeStateGilstate:         560,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.11.0 /home/korniltsev/.asdf/installs/python/3.11.0/lib/libpython3.11.so.1.0
	PythonVersion{3, 11, 0}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             -1,
		PyFrameObjectF_back:            16,
		PyFrameObjectF_code:            -1,
		PyFrameObjectF_frame:           24,
		PyFrameObjectF_localsplus:      -1,
		PyCodeObjectCoFilename:         112,
		PyCodeObjectCoName:             120,
		PyCodeObjectCoVarnames:         -1,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       32,
		PyRuntimeStateGilstate:         568,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.11.1 /home/korniltsev/.asdf/installs/python/3.11.1/lib/libpython3.11.so.1.0
	PythonVersion{3, 11, 1}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             -1,
		PyFrameObjectF_back:            16,
		PyFrameObjectF_code:            -1,
		PyFrameObjectF_frame:           24,
		PyFrameObjectF_localsplus:      -1,
		PyCodeObjectCoFilename:         112,
		PyCodeObjectCoName:             120,
		PyCodeObjectCoVarnames:         -1,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       32,
		PyRuntimeStateGilstate:         568,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.11.2 /home/korniltsev/.asdf/installs/python/3.11.2/lib/libpython3.11.so.1.0
	PythonVersion{3, 11, 2}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             -1,
		PyFrameObjectF_back:            16,
		PyFrameObjectF_code:            -1,
		PyFrameObjectF_frame:           24,
		PyFrameObjectF_localsplus:      -1,
		PyCodeObjectCoFilename:         112,
		PyCodeObjectCoName:             120,
		PyCodeObjectCoVarnames:         -1,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       32,
		PyRuntimeStateGilstate:         568,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.11.3 /home/korniltsev/.asdf/installs/python/3.11.3/lib/libpython3.11.so.1.0
	PythonVersion{3, 11, 3}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             -1,
		PyFrameObjectF_back:            16,
		PyFrameObjectF_code:            -1,
		PyFrameObjectF_frame:           24,
		PyFrameObjectF_localsplus:      -1,
		PyCodeObjectCoFilename:         112,
		PyCodeObjectCoName:             120,
		PyCodeObjectCoVarnames:         -1,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       32,
		PyRuntimeStateGilstate:         568,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
	// 3.11.4 /home/korniltsev/.asdf/installs/python/3.11.4/lib/libpython3.11.so.1.0
	PythonVersion{3, 11, 4}: {
		PyObjectObType:                 8,
		PyTypeObjectTpName:             24,
		PyThreadStateFrame:             -1,
		PyFrameObjectF_back:            16,
		PyFrameObjectF_code:            -1,
		PyFrameObjectF_frame:           24,
		PyFrameObjectF_localsplus:      -1,
		PyCodeObjectCoFilename:         112,
		PyCodeObjectCoName:             120,
		PyCodeObjectCoVarnames:         -1,
		PyTupleObjectObItem:            24,
		PyInterpreterFrameF_code:       32,
		PyRuntimeStateGilstate:         568,
		GilstateRuntimeStateAutoTSSkey: 24,
		PyTssT_key:                     4,
		StringSize:                     48,
	},
}
