// SPDX-License-Identifier: AGPL-3.0-only
// Provenance-includes-location: https://github.com/cortexproject/cortex/blob/master/pkg/frontend/v2/frontendv2pb/frontend.proto
// Provenance-includes-license: Apache-2.0
// Provenance-includes-copyright: The Cortex Authors.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: frontend/frontendpb/frontend.proto

package frontendpb

import (
	stats "github.com/grafana/pyroscope/pkg/querier/stats"
	httpgrpc "github.com/grafana/pyroscope/pkg/util/httpgrpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryID       uint64                 `protobuf:"varint,1,opt,name=queryID,proto3" json:"queryID,omitempty"`
	HttpResponse  *httpgrpc.HTTPResponse `protobuf:"bytes,2,opt,name=httpResponse,proto3" json:"httpResponse,omitempty"`
	Stats         *stats.Stats           `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResultRequest) Reset() {
	*x = QueryResultRequest{}
	mi := &file_frontend_frontendpb_frontend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResultRequest) ProtoMessage() {}

func (x *QueryResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_frontendpb_frontend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResultRequest.ProtoReflect.Descriptor instead.
func (*QueryResultRequest) Descriptor() ([]byte, []int) {
	return file_frontend_frontendpb_frontend_proto_rawDescGZIP(), []int{0}
}

func (x *QueryResultRequest) GetQueryID() uint64 {
	if x != nil {
		return x.QueryID
	}
	return 0
}

func (x *QueryResultRequest) GetHttpResponse() *httpgrpc.HTTPResponse {
	if x != nil {
		return x.HttpResponse
	}
	return nil
}

func (x *QueryResultRequest) GetStats() *stats.Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type QueryResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResultResponse) Reset() {
	*x = QueryResultResponse{}
	mi := &file_frontend_frontendpb_frontend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResultResponse) ProtoMessage() {}

func (x *QueryResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_frontendpb_frontend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResultResponse.ProtoReflect.Descriptor instead.
func (*QueryResultResponse) Descriptor() ([]byte, []int) {
	return file_frontend_frontendpb_frontend_proto_rawDescGZIP(), []int{1}
}

var File_frontend_frontendpb_frontend_proto protoreflect.FileDescriptor

const file_frontend_frontendpb_frontend_proto_rawDesc = "" +
	"\n" +
	"\"frontend/frontendpb/frontend.proto\x12\n" +
	"frontendpb\x1a\x19querier/stats/stats.proto\x1a\x1cutil/httpgrpc/httpgrpc.proto\"\x8e\x01\n" +
	"\x12QueryResultRequest\x12\x18\n" +
	"\aqueryID\x18\x01 \x01(\x04R\aqueryID\x12:\n" +
	"\fhttpResponse\x18\x02 \x01(\v2\x16.httpgrpc.HTTPResponseR\fhttpResponse\x12\"\n" +
	"\x05stats\x18\x03 \x01(\v2\f.stats.StatsR\x05stats\"\x15\n" +
	"\x13QueryResultResponse2f\n" +
	"\x12FrontendForQuerier\x12P\n" +
	"\vQueryResult\x12\x1e.frontendpb.QueryResultRequest\x1a\x1f.frontendpb.QueryResultResponse\"\x00B\x9d\x01\n" +
	"\x0ecom.frontendpbB\rFrontendProtoP\x01Z4github.com/grafana/pyroscope/pkg/frontend/frontendpb\xa2\x02\x03FXX\xaa\x02\n" +
	"Frontendpb\xca\x02\n" +
	"Frontendpb\xe2\x02\x16Frontendpb\\GPBMetadata\xea\x02\n" +
	"Frontendpbb\x06proto3"

var (
	file_frontend_frontendpb_frontend_proto_rawDescOnce sync.Once
	file_frontend_frontendpb_frontend_proto_rawDescData []byte
)

func file_frontend_frontendpb_frontend_proto_rawDescGZIP() []byte {
	file_frontend_frontendpb_frontend_proto_rawDescOnce.Do(func() {
		file_frontend_frontendpb_frontend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frontend_frontendpb_frontend_proto_rawDesc), len(file_frontend_frontendpb_frontend_proto_rawDesc)))
	})
	return file_frontend_frontendpb_frontend_proto_rawDescData
}

var file_frontend_frontendpb_frontend_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_frontend_frontendpb_frontend_proto_goTypes = []any{
	(*QueryResultRequest)(nil),    // 0: frontendpb.QueryResultRequest
	(*QueryResultResponse)(nil),   // 1: frontendpb.QueryResultResponse
	(*httpgrpc.HTTPResponse)(nil), // 2: httpgrpc.HTTPResponse
	(*stats.Stats)(nil),           // 3: stats.Stats
}
var file_frontend_frontendpb_frontend_proto_depIdxs = []int32{
	2, // 0: frontendpb.QueryResultRequest.httpResponse:type_name -> httpgrpc.HTTPResponse
	3, // 1: frontendpb.QueryResultRequest.stats:type_name -> stats.Stats
	0, // 2: frontendpb.FrontendForQuerier.QueryResult:input_type -> frontendpb.QueryResultRequest
	1, // 3: frontendpb.FrontendForQuerier.QueryResult:output_type -> frontendpb.QueryResultResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_frontend_frontendpb_frontend_proto_init() }
func file_frontend_frontendpb_frontend_proto_init() {
	if File_frontend_frontendpb_frontend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frontend_frontendpb_frontend_proto_rawDesc), len(file_frontend_frontendpb_frontend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_frontend_frontendpb_frontend_proto_goTypes,
		DependencyIndexes: file_frontend_frontendpb_frontend_proto_depIdxs,
		MessageInfos:      file_frontend_frontendpb_frontend_proto_msgTypes,
	}.Build()
	File_frontend_frontendpb_frontend_proto = out.File
	file_frontend_frontendpb_frontend_proto_goTypes = nil
	file_frontend_frontendpb_frontend_proto_depIdxs = nil
}
